### ISSUE TITLE
Export only available as text file?

### ISSUE THREAD

**Issue by arun-gurung** [suurjaak/Skyperious#101]
Skyperious can find my main chat and I can export also, but when I save it, the file chooser says it's a HTML-file, but the export is just a plain text file?

**Comment by suurjaak** [comment]
Can you describe in more detail, what steps you took and what was the result?

**Comment by arun-gurung** [comment]
As you know, I had to reinstall my system. Now everything looks correct and follow the usual steps like before, I select my chat and choose "export selected chat into individual files". In the "Save" dialogue, it says it saves as HTML but the end result is just a plain text file, although the chat is nicely formatted there.

**Comment by suurjaak** [comment]
What happens if you try the other export formats?

**Comment by arun-gurung** [comment]
Well, in the save dialogue box, there is no automatic file extension name. If I write manually that the file will end with .html then it exports correctly. The other formats also work.

**Comment by suurjaak** [comment]
Oho, looks like the file dialog behaves a bit differently under Linux. Will be fixed in an upcoming release. 

Another workaround for now - open the chat in Skyperious and use the "Export messages to file" button, this seems to set the format correctly.

**Comment by arun-gurung** [comment]
OK thanks for another workaround.

Before you close the issue, I just wanna know why you can export pictures but no videos, voice messages, PDFs or other documents?

**Comment by suurjaak** [comment]
Shared videos and voice messages *are* exported, if available from Skype online. Other shared file contents in general are not - because a shared file can be hundreds of megabytes. 

Although maybe I could provide that as a separate option.. 

But Skype retains shared files online only for 30 days (https://support.skype.com/en/faq/FA34644/skype-file-sharing-file-types-size-and-time-limits). 

(I will keep this issue open until releasing a fix for the format selection)

**Comment by arun-gurung** [comment]
I have a video and voice messages which are newer than 30 days. I exported into HTML with shared media in a separate folder and there were only pictures there.

**Comment by suurjaak** [comment]
Can you do this:

- open the chat in Skyperious
- open the Python console
- execute `page.stc_history.GetMessage(`index`)["body_xml"]`, where `index` is the index of the audio/video message in currently shown messages (can be negative if counting from the end, e.g. -1 is the last)

What does it print? 

If the result is something like `<URIObject uri="https://api.asm.skype.com/v1/objects/0-weu-d8-.....`, what is the result if you copy the `uri`-value and execute `db.live.get_api_media(that_copied_value, "video")` (or `"audio"` if voice message)? If the result is empty, was there an error printed to the log window?

**Comment by arun-gurung** [comment]
It prints this, I don't get any URI.

>>> page.stc_history.GetMessage(-1)["body_xml"]
u'<files><file index="0" size="18023933">video937d29a9-8f4f-486a-af95-491aaa280a8bvideo.mp4</file></files>'

**Comment by suurjaak** [comment]
Sorry, did not understand - what picture URI did you try with? 

But it looks like this message was not a video message, but a shared file instead. 

If you're willing to try further:

- open the chat in Skyperious
- open the Python console
- execute `chat = db.live.skype.chats[live.identity_to_id(page.chat["identity"])]`
- execute `for msg in chat.getMsgs(): print repr(msg)` over and over again until it reaches the message in question

What does the printed message look like? 

(Btw, to avoid formatting issues with copy-pasted data as you seemed to have with your last comment, you can attach it as a file instead)

**Comment by arun-gurung** [comment]
I executed `db.live.get_api_media(my_URI, "picture")` and got a lot of encoded output that made no sense.

When I execute "chat = db.live.skype.chats[live.identity_to_id(page.chat["identity"])]" I get:

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'chats'`

Then I execute "for msg in chat.getMsgs(): print repr(msg)" I get:

`for msg in chat.getMsgs(): print repr(msg)
for msg in chat.getMsgs(): print repr(msg)
  File "<input>", line 2
    for msg in chat.getMsgs(): print repr(msg)`

**Comment by suurjaak** [comment]
And the `my_URI` was what exactly? 

Oops, forgot to specify the first step:
- log in to Skype on the Online-page

**Comment by arun-gurung** [comment]
`my_URI` was just a copy and paste from the Skyperious chat window, there was a link to a picture there.

I logged in and now I don't  get a traceback error, but just empty output and get back to the prompt.

**Comment by suurjaak** [comment]
Yes, "share with Skype" means it's an ordinary file sharing. Sending an audio/video *message* is a different action inside Skype, where you record a clip to send. 

Do you have any *such* messages that are not getting exported?

**Comment by arun-gurung** [comment]
The last video I sent was live recorded from inside Skype, but I guess it was sent as a file. I did not select an already stored video from the disk.

No, I have only luck with exporting picture and nothing else.

**Comment by arun-gurung** [comment]
I sent a voice message via Android and there is no URI, the Skyperious chat log says "Sent file 1-audioMessage.m4a". So, I guess it downloads only files that are uploaded to the Skype sky.

I see you have no comment, so it can be a feature request. For example, optional choice to download attachments and a warning if the files are very big.

**Comment by suurjaak** [comment]
The newly released Skyperious v4.8 fixes the export type issue on Linux. 

Can you confirm that the export issue is cleared? 

---

It also downloads shared files in HTML export, if you choose the "HTML document with shared files in subfolder" type. 

For that you need to re-synchronize the database from online, Can you confirm that it works for you? At least for recently shared files; there is some limit on how long the files are kept in Skype online.

**Comment by arun-gurung** [comment]
Yes, now the export file extension issue is resolved.

I exported my chat with only a single picture and everything went well. Then now I sent a video and a voice message for test and now I get an error during export, here's a screenshot. [https://i.imgur.com/N3jkPw8.png](url)

**Comment by suurjaak** [comment]
Please reinstall the latest Skyperious and try again. A bug had crept in, I've updated the sources.

**Comment by arun-gurung** [comment]
I updated and now there is no export error, but alas it exported only an image and nothing else.

**Comment by suurjaak** [comment]
What if you send an ordinary file, does that get included in the "HTML document with shared files in subfolder" export?

**Comment by arun-gurung** [comment]
It successfully exported a PDF file, but still not the video and voice message.

**Comment by suurjaak** [comment]
Excellent that the file retrieval in general works. 

Closing this issue, as the original problem was solved. 

Can you open a new issue if video/audio messages are not being downloaded? And describe there more precisely what the export result was.
