### ISSUE TITLE
Exception: Multiline text items are not allowed 

### ISSUE THREAD

**Issue by vfedorov** [suurjaak/Skyperious#103]
Getting an exception:
`Multiline text items are now allowed without the ULC_HAS_VARIABLE_ROW_HEIGHT style`
when trying to view logs of one old chat: https://prnt.sc/1smh0u1
Is it possible just to ignore the corrupted message and show the another ones?

**Comment by suurjaak** [comment]
Where exactly is this coming from?

Can you copy-paste more details from the log (menu Help -> Show log window)?

**Comment by suurjaak** [comment]
Hello?

**Comment by suurjaak** [comment]
Fixed in the newly released version 5.0.
