### ISSUE TITLE
installing skperious on mac M1 fails with "ERROR: failed building wxWidgets"

### ISSUE THREAD

**Issue by birdridge** [suurjaak/Skyperious#104]
Hello,

I am trying to get skyperious installed and running on a Macbook Air M1, Mac OS 11.6

I used Terminal: pip install skyperious
Please does anyone have an idea what I could try to get skyperious installed onto my computer or running on it somehow?

Thanks

-----

1 error generated.
    /private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/build/wxbld/bk-deps g++ -std=gnu++11 -mmacosx-version-min=10.10 -c -o coredll_popupcmn.o    -I/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/ext/wxWidgets/src/jpeg -I/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/ext/wxWidgets/src/png -I/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/ext/wxWidgets/src/zlib -I/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/ext/wxWidgets/src/regex  -I/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/build/wxbld/lib/wx/include/osx_cocoa-unicode-3.1 -I/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/ext/wxWidgets/include -D_FILE_OFFSET_BITS=64  -D__WXOSX_COCOA__      -DWXBUILDING -DWXUSINGDLL -DWXMAKINGDLL_CORE -DwxUSE_BASE=0 -dynamic -fPIC -DPIC -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wno-deprecated-declarations -O2 -fno-common  -fvisibility=hidden -fvisibility-inlines-hidden   /private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/ext/wxWidgets/src/common/popupcmn.cpp
    make: *** [coredll_imagtiff.o] Error 1
    make: *** Waiting for unfinished jobs....
    Error building
    ERROR: failed building wxWidgets
    Traceback (most recent call last):
      File "build.py", line 1510, in cmd_build_wx
        wxbuild.main(wxDir(), build_options)
      File "/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/buildtools/build_wxwidgets.py", line 496, in main
        exitIfError(wxBuilder.build(dir=buildDir, options=args), "Error building")
      File "/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/buildtools/build_wxwidgets.py", line 85, in exitIfError
        raise builder.BuildError(msg)
    BuildError
    Finished command: build_wx (3.471s)
    Finished command: build (3.471s)
    Command '"/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python" -u build.py build' failed with exit code 1.
    
    ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/setup.py'"'"'; __file__='"'"'/private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-install-Vdud8Y/wxpython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sk/qpk_nn450s50g8461gb58ttw0000gn/T/pip-record-T6CjSZ/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/wxPython Check the logs for full command output.

**Comment by suurjaak** [comment]
Unfortunately, Macs are rather unknown territory for me. 

This is a general issue with getting wxPython installed. I assume `pip install wxPython` or pip `install -U wxPython` fail equally? 

If I had to hazard a guess, this is due to needing the older version of Python, 2.7. OS support for it has been steadily deteriorating in recent years. 

If you are using any other package managers, like conda, perhaps you can get wxPython installed via them?

Another option - Skyperious has a [Dockerfile](https://github.com/suurjaak/Skyperious/blob/master/build/README%20for%20Docker.md). But again, I am unfamiliar with using Docker on Mac.

**Comment by suurjaak** [comment]
The newly released version 5.0 ought to be easier to install, as Skyperious can now use Python 3.

**Comment by suurjaak** [comment]
Skyperious is now also installable via Snap.
