### ISSUE TITLE
Error installing due to wxpython error. Why is there no AppImage or Snap?

### ISSUE THREAD

**Issue by typoworx-de** [suurjaak/Skyperious#105]
Hello,
Trying to install this, but even using venv this fails with conflicts to ubuntu system-packages.

It would be awesome to have an AppImage or Snap installer for this tool.

**Comment by suurjaak** [comment]
I have zero experience with creating AppImages or snaps. Is this something you have experience with?

**Comment by suurjaak** [comment]
The newly released version 5.0 ought to be easier to install, as Skyperious can now use Python 3.

**Comment by suurjaak** [comment]
Skyperious is now installable via Snap.
