### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by FreddyD5** [suurjaak/Skyperious#109]
Hi, I just installed the app on Windows 10 PC but it's not letting me log in. Everything is grayed out?

![image](https://user-images.githubusercontent.com/68396409/169344714-0ac6dde2-1e6b-4a39-a011-2d927ea6e228.png)

**Comment by suurjaak** [comment]
Confirmed, there is a bug in the latest 32-bit version. 

Can you try installing the 64-bit version?

**Comment by FreddyD5** [comment]
Thanks, 64-bit is working fine.

**Comment by suurjaak** [comment]
Excellent, glad to hear that.

I also updated the 32-bit versions, everything should work now.
