### ISSUE TITLE
Error calling <bound method SkypeChat.getMsgs

### ISSUE THREAD

**Issue by ingenuitor** [suurjaak/Skyperious#113]
Hello, first I want to say I love the idea of your software if I can get it to work.  So far it's failing for me and I'm not sure why.  I really need to find a clean way to copy and or share a chat log and I have yet to find that.  Can you please advise and thank you for all your hard work.

`2022-11-08` 07:46:07.312 Error calling <bound method SkypeChat.getMsgs of SkypeSingleChat(id='8:live:.cid.XXX', alerts=True, userId='live:.cid.XXX')>.

Traceback (most recent call last):
File "skyperious\live.py", line 229, in request
File "skpy\chat.py", line 71, in getMsgs
File "skpy\conn.py", line 261, in syncStateCall
File "skpy\conn.py", line 237, in __call__
skpy.core.SkypeApiException: ('400 response from GET https://azscus1-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:live:.cid.XXX/messages', <Response `[400]>)`

**Comment by suurjaak** [comment]
Do I understand correctly that you're trying to sync a conversation from Skype online, and the sync fails?

Does it fail for all chats, or only this one? 

Is the chat history visible in the Skype online web page?

**Comment by suurjaak** [comment]
@ingenuitor Ping?

**Comment by suurjaak** [comment]
Two months have passed, no further information forthcoming: closing the issue.
