### ISSUE TITLE
Error loading group chat ...

### ISSUE THREAD

**Issue by timm735** [suurjaak/Skyperious#114]
hi =)
this error pops up when i open one of my chats:

Traceback (most recent call last):
File "skyperious\gui.py", line 5748, in load_chat
File "skyperious\gui.py", line 8273, in Populate
File "skyperious\gui.py", line 8070, in RefreshMessages
File "skyperious\skypedata.py", line 1842, in parse
File "skyperious\skypedata.py", line 2106, in parse_message_dom
AttributeError: 'NoneType' object has no attribute 'get'

it's a very large chat, about 500000 messages. could it be an out of memory?
so what exactly happens:
- synchronize history ends with no visuable error
- opening other smaller chats works
- now i open the big chat and i get this error. skyperious shows nothing of the chat
- when i try to open the other chats, they are now broken too (empty, no error message)
- exporting the big chat (csv) stops a month before the end (the years before are visuable)
- searching for the next, not exported message in the skyperious database view is succsessful

i hope this was a bit helpful? and thanks for this nice tool.

edit: the skype app shows all the missing messages
edit2: latest version, 5.3 64bit stand-allone

**Comment by suurjaak** [comment]
This looks like a known issue, a problem not with size but with message parsing. It is already fixed in development, but I have not gotten around to making a new release yet. Hopefully I have time over the weekend to finally do so. 

But in the meantime you could try this pre-release version: https://erki.lap.ee/stuff/skyperious_5.4.dev64_x64.exe.

**Comment by timm735** [comment]
Indeed, thank you very much.
Bug: fixed
You: hero

**Comment by suurjaak** [comment]
v5.4 has now been released as well.

**Comment by timm735** [comment]
Thank you very much for the reminder.

**Comment by timm735** [comment]
Hope you had some chilled holidays...
Its the first time I used the v5.4 and I see exactly the same error-message like in v5.3 when I want to show or export a chat:

...
File "skyperious\skypedata.py", line 1842, in parse
File "skyperious\skypedata.py", line 2106, in parse_message_dom
AttributeError: 'NoneType' object has no attribute 'get'

The previous Beta "skyperious_5.4.dev64_x64.exe" still works without any errors. You accidently uploaded the wrong exe? =)

![error](https://user-images.githubusercontent.com/117967569/210187556-06331053-0830-425d-99fe-1425597f5c27.JPG)

**Comment by timm735** [comment]
Ok, tested "skyperious_5.4.1_x64.exe" with the old, merged, large chat. It feels like if this works, your parsing-code is very stable =)

- Sync with "check older database chats" and "contact update": ok
- Showing the whole chat "from the beginning": ok
- Export "selected chat into individual file" (HTML with media-subfolder): ok - it produced a 174 MB HTML-file =)
- Export "selected chat into individual file" (CSV): ok

Thats what I use normally and it seems like parsing works perfect now. If you think I should test something else just post it.

**Comment by suurjaak** [comment]
Thank you, that is quite sufficient. Looks all good now, I've made a public release of v5.4.1.
