### ISSUE TITLE
CSV export formating to bypass commas "," . Errors when importing CSV to other services

### ISSUE THREAD

**Issue by fl0oo** [suurjaak/Skyperious#120]
would it be possible to add ["] quote marke arround each text chats (or any other effective workaround) in CSV so that importing to other services doesn't cause any issue ?

(trying to import CSV to notion but impossible. Errors since there are inevitably commas in the chat texts) 

Thanks

**Comment by suurjaak** [comment]
The CSVs exported from Skyperious use semicolon for column delimiter. 

As such, if the other service already recognizes that the file columns are separated by semicolons, it should not be reading commas as delimiters. 

Perhaps a solution would be to export the chats from Skyperious as Excel workbooks instead?

**Comment by suurjaak** [comment]
@fl0oo Any updates?
