### ISSUE TITLE
"Scan and report" issue In Windows GUI (comparing databases before merge)

### ISSUE THREAD

**Issue by fl0oo** [suurjaak/Skyperious#121]
Not able to merge after launching "a scan and report". 
Buttons are greyed and and you have to start over chosing the databases to compare/merge
![Capture d’écran (239)](https://github.com/suurjaak/Skyperious/assets/98915524/40c3ab6e-f045-4a75-bbf2-2fa5fc416844)

**Comment by suurjaak** [comment]
From the screenshot, it appears there was nothing to merge from the left side to the right? Apparently the right side already has all the data that is present on the left, so this result is expected.

**Comment by fl0oo** [comment]
> From the screenshot, it appears there was nothing to merge from the left side to the right? Apparently the right side already has all the data that is present on the left, so this result is expected.

Thx for your answer (and your very usefull work, I use Skype a lot these days to leverage Bing chat and keep trace of chats)

Regarding the issue, The thing is that if this screen/tab kind of freezes after a scan that results in [no changes identified], it then can't take into account if those databases are updated in the meantime. 
The issue is not exactly related to the printed result.

+++ I'd like this "DB comparison" tab with those specific selected DB to stay open for quick access to merge these after a sync from skype servers

**Comment by suurjaak** [comment]
But the solution is trivial: just reopen the comparison. 

Yes, swapping left-right does not reload the database state, as loading it all can take some time.

**Comment by fl0oo** [comment]
Obviously the command line tool option will better suit my needs. Thx for your time 🙏
