### ISSUE TITLE
I cannot find a main.db file in my Skype folder on Mac, even though I know I chatted on Skype in 2016.

### ISSUE THREAD

**Issue by NylaTheWolf** [suurjaak/Skyperious#122]
I'm on Mac Catalina and I wanted to find the old conversations of my friend and I when we chatted on Skype. But I cannot find the main.db file that should exist. This Mac was used to chat with my friend, albeit I had to wipe it and restore data years ago when I upgraded it, but I still have the backups from right before I did that. It's possible that perhaps the backups I made before the upgrade are on my other drives back at home, and perhaps I never restored the Skype history I had back then? I don't know. I am just at a loss as to why I don't have the main.db file that should apparently exist. I uninstalled Skype a while back, is that why the main.db disappeared? I don't know why only that file would've disappeared.

The path I'm looking at is `/Users/<username>/Library/Application Support/Skype`.

I just want to know if I'm looking in the right place. This is what the skype folder looks like.
![Screen Shot 2023-09-12 at 4 24 47 PM](https://github.com/suurjaak/Skyperious/assets/41797151/51d6d626-f8db-4c58-82cd-8a5f029367b2)

**Comment by suurjaak** [comment]
If the file dates are of the last time you used Skype there, then it looks like the Skype version was one that no longer used main.db files. In 2017 or so, Skype stopped keeping messages on user computers, storing them on their own servers instead. 

You may be able to export your old messages from the Skype web interface, if you log in to www.skype.com with your account, and go to _My account_ -> _Export files and chat history_ (at least that's where it was when I last looked). And this export can be imported in Skyperious. 

But it's very possible that your old messages are no longer available to you. Unless you can find the main.db in another backup.

**Comment by suurjaak** [comment]
@NylaTheWolf Any luck?

**Comment by suurjaak** [comment]
Closing the issue due to lack of feedback.
