### ISSUE TITLE
Exporting images inside HTML file

### ISSUE THREAD

**Issue by jkdn0921s** [suurjaak/Skyperious#124]
I've created a new database through File > New Database > From skype online, added username and password, and it worked to download all chats and groups locally. 
And at the end I was able to export a group chat history as HTML.

But the HTML file does not have images embedded inside it, and did not download the images locally.

All images in the HTML file have this text:
`To view this shared photo, go to: https://api.asm.skype.com/v1/objects/[...]/views/imgpsh_fullsize` where [...] is a long string of numbers and letters.

I checked File > Advanced Options > SharedImageAutoDownload is enabled.

Is this all I need to do to download the images and see them embedded inside the HTML file?
Or is there anything else I can do?

Thank you!

**Comment by suurjaak** [comment]
Your settings seem all good and should work. 

How old are the messages? There is a time limit to how long Skype will keep images on their servers. 

Can you see these images in the Skype web interface at www.skype.com? 

Once you have logged in to the Skype web interface in your browser, and you then click the link you saw in Skyperious, does the image open in your browser?

**Comment by jkdn0921s** [comment]
Thanks a lot suurjaak for replying back on this thread!

> How old are the messages? There is a time limit to how long Skype will keep images on their servers.

The group chat starts in 2021, but realistically I'd need it from 2022 onwards.

> Can you see these images in the Skype web interface at [www.skype.com](http://www.skype.com/)?
> 
> Once you have logged in to the Skype web interface in your browser, and you then click the link you saw in Skyperious, does the image open in your browser?

Yes, if I am logged in the browser in my Skype account (like Outlook login), and I click on the `https://api.asm.skype.com/v1/objects/[...]/views/imgpsh_fullsize` files, I can see the images in the browser.

But FYI when I exported my Skype history locally here [https://go.skype.com/export](https://go.skype.com/export), the Files export (which includes images and files) was a "media" folder with 30k+ files. So I am wondering maybe the export with Skype online is not working because I'd have so many files?

This got me thinking if it'd be possible to select only a specific group chat after logging with Skype online, that might reduce the number of images a lot and maybe it will work to download them inside the HTML file in Skyperious?

**Comment by suurjaak** [comment]
The number of files should not really affect whether any of them can be downloaded.

> if it'd be possible to select only a specific group chat after logging with Skype online

That is possible - there is a button "Synchronize selected chats" on the Online-page in Skyperious. 

However, images are not downloaded during the sync. Images are downloaded during export. 

After you run an export, open the log window in Skyperious (menu Help -> Show log window). Are there any errors logged there?

**Comment by jkdn0921s** [comment]
> That is possible - there is a button "Synchronize selected chats" on the Online-page in Skyperious.

I couldn't find this button, can you advise where it is? so do I have to create a new database again with Skyle Online and select this? 

I tried doing it a different way, and I selected a group chat in Skyperious > then Right click on it > Export to file

And I got this error in the log tab:

`2023-12-21 17:54:49.858	Started application.
2023-12-21 17:55:26.892	Opened /home/user/snap/skyperious/3/.local/share/skyperious/myskype.username.main.skype.online.db (148.38 MB).
2023-12-21 17:56:26.506	Exporting to /home/user/Documents/Skyperious/Skype group chat ABC Group.html.
2023-12-21 17:56:26.506	Exporting 1 chat from /home/user/snap/skyperious/3/.local/share/skyperious/myskype.username.main.skype.online.db as HTML to /home/user/Documents/Skyperious/Skype group chat ABC Group.html.
2023-12-21 17:56:26.506	Exporting group chat "ABC Group ".
2023-12-21 17:56:27.022	Error parsing message 43265, body "[1676573253] AnotherUser: To view this card, go to: <a href="https://go.skype.com/cards.unsupported">https://go.skype.com/cards.unsupported</a>

			<<< Aw, come on man!  I'm way better looking than that!!  ".

			Traceback (most recent call last):
			  File "/snap/skyperious/3/lib/python3.6/site-packages/skyperious/skypedata.py", line 2329, in make_xml
			    result = ElementTree.fromstring(TAG % text)
			  File "/snap/skyperious/3/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
			    parser.feed(text)
			  File "<string>", line None
			xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 3, column 1

			During handling of the above exception, another exception occurred:

			Traceback (most recent call last):
			  File "/snap/skyperious/3/lib/python3.6/site-packages/skyperious/skypedata.py", line 2333, in make_xml
			    result = ElementTree.fromstring(TAG % text)
			  File "/snap/skyperious/3/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
			    parser.feed(text)
			  File "<string>", line None
			xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 3, column 1

			During handling of the above exception, another exception occurred:

			Traceback (most recent call last):
			  File "/snap/skyperious/3/lib/python3.6/site-packages/skyperious/skypedata.py", line 2337, in make_xml
			    result = ElementTree.fromstring(TAG % text)
			  File "/snap/skyperious/3/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
			    parser.feed(text)
			  File "<string>", line None
			xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 3, column 1

2023-12-21 17:56:28.535	Exported 6,388 messages to /home/user/Documents/Skyperious/Skype group chat ABC Group.html.
`

FYI I am on Linux Mint 21.1 Cinnamon, Linux Kernel 6.1.0-1027-oem if that helps in any way.

**Comment by suurjaak** [comment]
The "Synchronize selected chats" button is on the Online-page of the database tab in Skyperious. 

That error message is unrelated to shared image download and embedding.

Perhaps the matter here is just that you are not logged in while exporting. Try this:

- open the database in Skyperious
- go to the Online-page
- enter your password and click "Log in as .."
- and now export some chat as HTML

And if you check the box "Remember password" on the Online-page, next time Skyperious will auto-login when you export a chat as HTML.

**Comment by jkdn0921s** [comment]
Thank you so much suurjaak, it worked like a charm!

It was a bit confusing where is the Online one, but realised it's in the bottom left. Went there, logged in as username, then clicked Syncronize selected chats.

Then it worked to sync even though FYI I got the messages sometimes that Skyperious is not responding, I'd click on Wait and it downloads all the images inside the embedded HTML.

**If I click "Remember password", do I have to click also "Check older database chats for messages to sync"? If i want to get the existent .HTML group chat updated everytime I open Skyperious?

Or will I have to synchronize it all the time, and wait for it to re-download it as a new HTML file?**

Thank you!

**Comment by suurjaak** [comment]
Excellent, glad to hear it worked. 

The "not responding" thing is a limitation of the programming language used - it is so busy working on the export that it does not get around to refreshing the program screen often enough, which can make the operating system think the program has stalled. It's harmless. 

> do I have to click also "Check older database chats for messages to sync"?

No, that is for really older chats; like chats in your local database that have not had any online traffic for over a year. 

But you do need to do the sync from time to time if you want your local database to be up to date. The export only operates on your local database, the only thing it takes from online are shared files. 

There are other checkboxes there like "Log in automatically" and "Synchronize history automatically". Checking these will cause Skyperious to update your local database every time you open it.

**Comment by jkdn0921s** [comment]
awesome thanks a lot @suurjaak ! super appreciated! it's working great now! thx!
