### ISSUE TITLE
Delete from Skype but retain offline

### ISSUE THREAD

**Issue by ozarugit** [suurjaak/Skyperious#125]
Skype has got very slow displaying/updating/searching messages on desktop (Win10) and mobile (Android), and it's been suggested that might be because of large archives of past messages - so I'm intending to delete all past messages from my online Skype account, but want to save a copy first. Skype's own Export function isn't very user-friendly, so I'm exploring Skyperious instead. So far so good.

However, am I right to think that if I synch all messages in Skyperious, then delete on Skype, then synch again in Skyperious, the synching will delete all messages in the downloaded database too? I guess that's intentional, but it's not what I want.

So is the way to achieve a "backup then purge" as I want as follows? 1) Synch, 2) in Skyperious, save to a renamed 'backup' db or XLSX etc., 3) Delete online, 4) Synch again whenever wanted (e.g. if it seems to slow down again).

**Comment by suurjaak** [comment]
Syncing from live in Skyperious only deletes message content from the local database if message author has explicitly removed the message. 

I have not used Skype's "Clear conversation" and "Delete conversation" functions myself, but I doubt that these merely mark the messages as deleted; I would assume these actually delete the messages completely from the user's history. In that case, nothing is removed in Skyperious sync action. 

So I would expect that clearing a conversation will retain the history in Skyperious as is. But in any case, I would recommend making a backup of your database file before trying this.
