### ISSUE TITLE
Error exporting on Win10 and showing as Not Responding

### ISSUE THREAD

**Issue by wrtz008** [suurjaak/Skyperious#128]
I am trying to export a Group Chat to HTML through Skyperios version 5.6 and it's just hanging there as Not Responding on a Win10 22H2 machine, please check screenshots.

The resources are not an issue, I got plenty of RAM and CPU power.

I've already synced and saved the DB locally. The moment that I click on the specific Skype Group chat > right click > save as HTML > it just gets blocked and keeps hanging there indefinetely, not exporting.

Any Idea what else I can do?

PS: this has happened since I just updated, I've used it before and did not have this issue a few months ago.

Thank you!

![Win10 Export error Task Manager](https://github.com/user-attachments/assets/7f72ba8e-0d8d-4bfa-b15a-d671f6b28ee3)
![Win10 Export error](https://github.com/user-attachments/assets/686e354f-541e-4497-9b32-6f6e47d5ee4f)

**Comment by wrtz008** [comment]
Solution: wait a few more minutes, it works : )

**Comment by suurjaak** [comment]
Glad to hear it finally worked. 

But this sounds bad, there should not be such lags. Can you describe in more detail what happened - upon which action did it hang, and what was happening on screen? 

How it should work when right-clicking on a chat in the Chats-page:
- context menu opens
- when "Export to file" is selected, a file dialog opens
- when choice in file dialog is submitted, file dialog closes and an overlay panel opens, saying "Exporting to <that_selected_file>"
- once export finishes, the overlay panel is closed and the exported file is opened in browser

**Comment by wrtz008** [comment]
I did get to the Export to file option, and was able to select the file and give it a name, but after that it basically froze altogether and it shows as Not Responding both in the app window bar, and in Task Manager.

The archive was not that big it was for about 2 months :  /

**Comment by suurjaak** [comment]
So do I understand correctly - the program froze during the export for several minutes, but in the end did complete the export, and did open the resulting HTML file? 

A few more questions if you don't mind:
- What was the program's CPU usage during this freeze?
- Did the export also contain shared images?
- Does this occur every time you export this chat? What happens when you export a smaller chat?

**Comment by wrtz008** [comment]
@suurjaak sorry for the suuuper late reply on this thread! 
yes that is correct, program froze during the export for quite a few minutes. Just tested it again and it took a while. 

This is what it looks like in Task Manager after I click export locally (only one Skype group):

![skyperious error](https://github.com/user-attachments/assets/deecc587-2f24-42c5-b1ee-41b70a89a370)

Here are the answers to your questions:

- What was the program's CPU usage during this freeze?
Here is the CPU usage at about 17%:
![skypeious CPU](https://github.com/user-attachments/assets/010e2468-90b6-49ab-a6a6-4001e2a71ac8)

Here is each of CPUs threads, this time at 13% during same freeze:
![skypeious CPU2](https://github.com/user-attachments/assets/ea437af6-440d-4ecf-a701-2aa1ea150dd5)

FYI I am not running any other intensive apps when doing the export.

- Did the export also contain shared images?
Yes it contains images and they are displaying fine in the final .html file.
I assume you mean embedded images.

- Does this occur every time you export this chat? What happens when you export a smaller chat?
Yes it happens every single time I export this chat, it has 30k+ messages and was first created in 2021. I wonder maybe because it has so much history in it?!

I just tested it exporting again, it took about 25-30 mins to export the whole chat.

When I export a smaller chat it works fine, it's quick and instant, no issues with it.
