### ISSUE TITLE
OSX build relies on unavailable homebrew formulas (+ PIL is broken)

### ISSUE THREAD

**Issue by barneycarroll** [suurjaak/Skyperious#28]
The OSX build guide isn't possible at the moment:

* `brew install python2` should be `brew  install python`

None of the subsequent dependencies seemed to have homebrew formulas I could find. PIL has a suggested replacement of pillow (`brew install pillow`), but that would mean changing your code. None of the remaining dependencies have associated formulas; they can be installed with pip, which comes with the python brew in step 1 – the remaining formulas can then have `brew` replaced with `pip` and work correctly, except for PIL.

PIL seems to be outdated and derelict as far as modern package managers are concerned. I found [this post on the subject](http://stackoverflow.com/a/8864020/356541), which might work – you can override pip's new security features to force install PIL but the import statements in the python code still won't work.

**Comment by suurjaak** [comment]
With the new 3.3 version, Skyperious is now installable by pip. This does not help with wx, of course, but maybe helps getting everything else installed, including Skyperious itself. I'd be grateful if somebody could try it, as I have no Mac to test it myself.

**Comment by barneycarroll** [comment]
Cool! I'll give that a shot in the morning. For the record, I've convinced my colleagues that Skype is not fit for purpose and we've moved to Slack.

**Comment by suurjaak** [comment]
Closing the issue, as no more feedback coming. Please reopen if installing Skyperious on Mac is still problematical.
