### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by mherrmann3** [suurjaak/Skyperious#29]
First: thanks very much for this awesome tool! :smiley: Especially the export feature is quite useful (to have everything "portable" :stuck_out_tongue:)

Ok, some suggestions, *IF* you have time for them and/or consider them useful for yourself; mostly concerning the statistics:

1. Could you also make a histogram for the used emoticons; e.g., a multiple bar chart to account for each contact? That would be awesome!!! :heart_eyes: (or at least count them)
2. For the *word cloud*
 * Could you also *split* the info per contact? There could be two options: First: on word hover, just show who wrote this word how many times (plus, you could color the words with two colors - depending on who wrote a word more often). Or secondly, make a world cloud for each contact (less aesthetic). 
 * Can you you make it possible to set a *minimum word length* for the words to appear in the word cloud?
4. A histogram of the timely distribution of the messages would be nice. 
 * First, over the *time of day*; see [here (right column)](http://lemodule.free.fr/computer/programs/screenshots/Miranda_IM/HistoryStats.png) or [here (first screenshot, lower right "quadrant")](https://addons.mozilla.org/en-US/thunderbird/addon/mail-summaries/?src=userprofile)
 * Secondly, over the whole time span, e.g., to spot times of increased communication -- or non-communicating days. I spotted a good implementation of this in the search menu of Thunderbird ([see here for a good description if you don't have thunderbird](http://ux.stackexchange.com/a/56898), or [this](http://en.flossmanuals.net/thunderbird/searching-and-filtering-messages/)). Remember that this element only has to *present* the data - it doesn't have to act as a time filter. :wink:  

In case i have more suggestions, I update this comment.

Finally, the only bug I encountered (if we can even call it like that): When dragging the left time filter boundary more to the left, it kinda resets and drops to the right. Strange behavior. Probably a GUI issue.

Thanks again for your time and effort! (especially for offering it FOR FREE) :v:

**Comment by suurjaak** [comment]
A new Skyperious version, 3.3, has just been released, with per-contact word clouds, and 24h and date activity histograms.

**Comment by mherrmann3** [comment]
THANKS A LOT!!! Looks super-awesome! Really thanks for your (coding) work! ... Also for the HTML export. Great! I consider all this stuff quite useful and interesting; I hope you and others as well. :blush:  

I have no "complaints" any more :wink: You can relax now. :grinning:

**Comment by suurjaak** [comment]
You're welcome :)

**Comment by SzaraHill** [comment]
For what it's worth, the emoticon histogram is something I (and my chat partner) would be interested in.  Currently I have plans to use the table exports and Excel filters and formulas to try to work out our use of emoticons, but haven't yet started actually working on it.

More from curiosity than anything else; it's not a huge need - just wanted to chime in that there's more than one person with interest.  :D

**Comment by suurjaak** [comment]
Just mentioning here that Skyperious 3.5, released last week, has emoticon data in chat statistics, both in-program and in HTML export.

**Comment by mherrmann3** [comment]
Wooow! Amazing. Thanks a lot for this work! Just one example: I know now that I'm pretty boring with my loved one (#1 is ":-)"), however, pretty ironical ( ";-)" is #4). At least, ":-*" comes at #3 and "(hug)" at #5.

Want to share yours? ;-) :-D

Thanks again, Erki! For making it possible to explore the distribution of my emotions.
Also thanks for the flexible histogram of chat messages over time. Haven't shown you my appreciation enough yet. 

Ultimate would be to see a stacked histogram. That way, one could see/distinguish the emoji contribution of the the chat partner and myself. But that's super-optional.

That's all for now. Enjoy your summer!

**Comment by suurjaak** [comment]
You're welcome :)
