### ISSUE TITLE
Formatted text is not displayed correctly

### ISSUE THREAD

**Issue by Tails32** [suurjaak/Skyperious#31]
Since Skype's latest update it got a new design and begun to use formatting for text messages just like on Google+ or described in this blog post: http://blogs.skype.com/2014/10/16/instant-message-formatting-with-skype-for-mac-7-0/

Example: * word * = fat formatted word
Example: _ word _ = italic formatted word
Example: ~ word ~ = strikethrough word

Skyperious does not display italic text, while fat text is shown. I don't know if strikethrough text is displayed.

**Comment by suurjaak** [comment]
A new Skyperious version, 3.3, has just been released, with support for Skype 7 formatting.
