### ISSUE TITLE
Unexpected error when loading very large (80k+) chats.

### ISSUE THREAD

**Issue by rikai** [suurjaak/Skyperious#32]
Seeing this consistently whenever i try to load any large chats and then load their history 'from the beginning':

>23:23:10.121	An unexpected error has occurred:
>		
>		Traceback (most recent call last):
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\wx._misc", line 1367, in Notify
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\wx._core", line 16870, in Notify
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skyperious", line 5874, in filter_range
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skyperious", line 6058, in RefreshMessages
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1533, in parse
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1654, in parse_message_dom
>		UnboundLocalError: local variable 'b' referenced before assignment
>		
>23:23:10.608	Sent error report to http://erki.lap.ee/downloads/Skyperious/feedback (An unexpected error has occurred:
>		
>		Traceback (most recent call last):
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\wx._misc", line 1367, in Notify
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\wx._core", line 16870, in Notify
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skyperious", line 5874, in filter_range
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skyperious", line 6058, in RefreshMessages
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1533, in parse
>		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1654, in parse_message_dom
>		UnboundLocalError: local variable 'b' referenced before assignment
		).

After that, the chat panel is completely broken until i restart the app.

I'm assuming its anything with >50k lines. I have 2 chats, one with 80k and one with 810k lines that both trigger it. My next largest chats @ 34k and 30k do not trigger it.

I'd love to see it fixed, as i'd like to get stats and be able to export that extremely large one especially.

**Comment by DozeyM** [comment]
Yip, I'm getting a (very) similar error:
		
23:11:47.821	Sent error report to http://erki.lap.ee/downloads/Skyperious/feedback (An unexpected error has occurred:
		Exception in thread Thread-2:
		Traceback (most recent call last):
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\threading", line 810, in __bootstrap_inner
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\workers", line 390, in run
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\workers", line 424, in work_diff_left
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\workers", line 792, in get_chat_diff_left
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1533, in parse
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1654, in parse_message_dom
		UnboundLocalError: local variable 'b' referenced before assignment
		).

23:12:24.951	An unexpected error has occurred:
		Traceback (most recent call last):
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skyperious", line 5141, in on_change_list_chats
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\workers", line 792, in get_chat_diff_left
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1533, in parse
		  File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1654, in parse_message_dom
		UnboundLocalError: local variable 'b' referenced before assignment

**Comment by Gorbush** [comment]
I have the same thing while merging accounts - 124k and 39k messages.
Error merging chats:Traceback (most recent call last): File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\workers", line 487, in work_diff_merge_left File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\workers", line 792, in get_chat_diff_left File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1533, in parse File "C:\stuff\projektid\skyperious\packaging\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1654, in parse_message_dom UnboundLocalError: local variable 'b' referenced before assignment

**Comment by suurjaak** [comment]
Sorry for the late reply.

A new Skyperious version, 3.3 has just been released, where this error should be fixed. Can somebody confirm?

**Comment by Gorbush** [comment]
It Works!  Owesome!

**Comment by DozeyM** [comment]
Thanks!  Seems to be working for me now :)
I retried the merge of a large main_large.db into a small main.db which gave the error before and there are no errors :)

**Comment by suurjaak** [comment]
Excellent, thank you.
