### ISSUE TITLE
New message formats breaking some lines in Excel and CSV exports

### ISSUE THREAD

**Issue by SzaraHill** [suurjaak/Skyperious#37]
Very grateful for the inclusion of the new formatting characters in recent versions of Skyperious (as per [this issue](https://github.com/suurjaak/Skyperious/issues/31) ) - since formatting within cells is a tricky endeavour.  :thumbsup:

Unfortunately I've noticed that after exporting, some portions of lines following the underscore _ character are missing from my logs.  They're present in the program itself and the HTML exports, and I haven't checked the raw table exports yet to see if the issue exists there as well.

Example:
*original message*
> No problem, that was my _guess_ as-to what was going on.

*exported message*
> No problem, that was my `_guess_`

It seems that if there's an emoticon at the end of the message, that will be included even if the rest is cut off.

My great appreciation for looking into this, and for a fantastic program!

**Comment by suurjaak** [comment]
Confirmed, there's a bug in handling formatted messages in Excel/CSV/text exports.

A fixed release will come as soon as issue #33 is solved.

Thank you for reporting this, and glad to hear the program is fantastic :)

**Comment by SzaraHill** [comment]
Awesome, thanks so much for the quick attention to these issues!

Now, this isn't an issue per se, but if I may ask the question...  I'm not terribly familiar with databases, and I don't know how to filter the tables so that I can export only a specific time period.  Care to give me a hint?

**Comment by suurjaak** [comment]
I guess the easiest way would be to delete the messages you do not want. For example, to get export from 2014 only:

- make a copy of the database
- open the copy and execute this in SQL window:
`
DELETE FROM Messages WHERE DATE(timestamp, "unixepoch") < "2014-01-01" OR DATE(timestamp, "unixepoch") > "2014-12-31"`

- export from the copy

**Comment by suurjaak** [comment]
SzaraHill, can you check if this issue is properly fixed in the new v3.4.1 release?

**Comment by suurjaak** [comment]
Closing the issue, as the problem should be fixed in the newest release. Please reopen if that's not the case.
