### ISSUE TITLE
GUI doesn't start on Fedora 22

### ISSUE THREAD

**Issue by kostich** [suurjaak/Skyperious#44]
wxPython is installed, so are the pip modules from requirements.txt but GUI does not start. Command line options are working.

```
[user@host Skyperious] $ git log | head -n 5
commit ecc037581993a2adfdd489efb5d90ace974831c7
Author: Erki Suurjaak <erki@lap.ee>
Date:   Thu Jul 16 22:49:29 2015 +0300

    v3.5 checkpoint.
[user@host Skyperious] $ pwd
/home/user/izvorni/Skyperious
[user@host Skyperious] $ python --version
Python 2.7.10
[user@host Skyperious] $ python skyperious/main.py
[user@host Skyperious] $ python skyperious/main.py --verbose
usage: main.py [-h] [--verbose] {export,search,merge,diff,gui} ...
main.py: error: too few arguments
[user@host Skyperious] $ python skyperious/main.py --verbose gui
[user@host Skyperious] $ dnf list installed | grep wx
pymol-wxpython.x86_64                 1.7.6-1.20150610svn4121.fc22
wxBase.x86_64                         2.8.12-16.fc22            @fedora         
wxBase3.x86_64                        3.0.2-9.fc22              @updates `       
wxGTK.x86_64                          2.8.12-16.fc22            @fedora         
wxGTK-gl.x86_64                       2.8.12-16.fc22            @fedora         
wxGTK-media.x86_64                    2.8.12-16.fc22            @fedora         
wxGTK3.x86_64                         3.0.2-9.fc22              @updates        
wxGTK3-devel.x86_64                   3.0.2-9.fc22              @updates        
wxGTK3-gl.x86_64                      3.0.2-9.fc22              @updates        
wxGTK3-media.x86_64                   3.0.2-9.fc22              @updates        
wxGlade.noarch                        0.7.0-1.fc22              @updates        
wxPython.x86_64                       3.0.2.0-5.fc22            @System         
wxPython-devel.x86_64                 3.0.2.0-5.fc22            @fedora         
[user@host Skyperious] $ sudo pip install -r requirements.txt 
You are using pip version 7.0.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyparsing in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): Skype4Py in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): XlsxWriter in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from Skype4Py->-r requirements.txt (line 6))
[user@host Skyperious]
```

**Comment by suurjaak** [comment]
One possibility is that there is a mismatch between Python and wx. Your wx installation seems to be 64-bit - is the Python installation also 64-bit?

Does the wx library work otherwise? For instance, if you try running a simple script like https://github.com/wxWidgets/wxPython/blob/master/demo/About.py?

**Comment by kostich** [comment]
Both wx and Python are 64 bit.

I can run that simple script.

![about](https://cloud.githubusercontent.com/assets/4953862/10461678/c72b86f8-71da-11e5-86c2-0e1330e56625.png)

**Comment by suurjaak** [comment]
Then this is a bit harder to figure out..

Can you try one thing: open a shell console inside Skyperious' directory and run 
`python -m pdb skyperious/main.py`

It will start a prompt like

    > /home/user/Skyperious/skyperious/main.py(14)<module>()
    -> """
    (Pdb)

In the prompt type `continue` (or just `c`). This will run Skyperious in the Python debugger, which might show more information on crashing.

**Comment by kostich** [comment]
I've got this in a special "wxPython stout/stderr" window:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib64/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib64/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "skyperious/main.py", line 14, in <module>
    """
  File "skyperious/main.py", line 574, in run
    run_gui(arguments.FILE)
  File "skyperious/main.py", line 484, in run_gui
    window = sys.modules["main"].window = skyperious.MainWindow()
  File "skyperious/skyperious.py", line 120, in __init__
    self.create_page_main(notebook)
  File "skyperious/skyperious.py", line 577, in create_page_main
    button = controls.NoteButton(panel_main, label, note, img.Bitmap)
  File "skyperious/controls.py", line 331, in __init__
    self.WrapTexts()
  File "skyperious/controls.py", line 470, in WrapTexts
    self._text_note = WORDWRAP(self._text_note, width - 10 - x, dc)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/lib/wordwrap.py", line 27, in wordwrap
    pte = dc.GetPartialTextExtents(line)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_gdi.py", line 4161, in GetPartialTextExtents
    return _gdi_.DC_GetPartialTextExtents(*args, **kwargs)
PyAssertionError: C++ assertion "m_graphicContext" failed at ./src/common/dcgraph.cpp(1175) in DoGetPartialTextExtents(): wxGCDC(cg)::DoGetPartialTextExtents - invalid DC
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
```

**Comment by MaineCoonz** [comment]
I am sorry to say that I have exactly the same problem as kostich.
I installed Skyperious version 3.5 on Aug.03.2016, Fedora 24 Workstation.
Linux 4.6.4-301.fc24.x86_64 #1 SMP Tue Jul 12 11:50:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
I can replicate everything above, with a few minor differences:
----------
[user@host Skyperious] $ python --version
Python 2.7.12
[user@host Skyperious] $ dnf list installed | grep wx
wxBase3.x86_64                         3.0.2-19.fc24            @fedora         
wxGTK3.x86_64                          3.0.2-19.fc24            @fedora         
wxGTK3-devel.x86_64                3.0.2-19.fc24            @fedora         
wxGTK3-gl.x86_64                      3.0.2-19.fc24            @fedora         
wxGTK3-media.x86_64               3.0.2-19.fc24            @fedora         
wxPython.x86_64                        3.0.2.0-10.fc24          @fedora         
[user@host Skyperious] $ sudo pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup4 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyparsing in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): Skype4Py in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): XlsxWriter in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from Skype4Py->-r requirements.txt (line 6))
----------
I can run the simple script About.py
----------
... open a shell console inside Skyperious' directory and run python -m pdb skyperious/main.py
Here is the traceback:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib64/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib64/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "skyperious/main.py", line 14, in <module>
    """
  File "skyperious/main.py", line 574, in run
    run_gui(arguments.FILE)
  File "skyperious/main.py", line 484, in run_gui
    window = sys.modules["main"].window = skyperious.MainWindow()
  File "skyperious/skyperious.py", line 120, in __init__
    self.create_page_main(notebook)
  File "skyperious/skyperious.py", line 577, in create_page_main
    button = controls.NoteButton(panel_main, label, note, img.Bitmap)
  File "skyperious/controls.py", line 331, in __init__
    self.WrapTexts()
  File "skyperious/controls.py", line 470, in WrapTexts
    self._text_note = WORDWRAP(self._text_note, width - 10 - x, dc)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/lib/wordwrap.py", line 27, in wordwrap
    pte = dc.GetPartialTextExtents(line)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_gdi.py", line 4161, in GetPartialTextExtents
    return _gdi_.DC_GetPartialTextExtents(*args, **kwargs)
PyAssertionError: C++ assertion "m_graphicContext" failed at ./src/common/dcgraph.cpp(1175) in DoGetPartialTextExtents(): wxGCDC(cg)::DoGetPartialTextExtents - invalid DC
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
----------
I can send you the output from strace if it would be jelpful.

**Comment by MaineCoonz** [comment]
I downloaded the fixed file controls.py from GitHub, and tried again.
Now I get a new python error:  'No module named dbus'.
It turns out that "python-dbus-common" and also "python2-dbus" are required.  Unfortunately Fedora 24 does not seem to provide either of these; nevertheless I installed "dbus-python-devel-1.2.4-1.fc24.x86_64".
But skyperious still will not run; it just dies silently.

However, this works:
[user@host Skyperious] $ python -m pdb skyperious/main.py
Skyperious will start like this, and seems to run fine.
There is no traceback output of any kind.

**Comment by qtlin** [comment]
Running from 3.5 zip file shows the same PyAssertionError as above, but 
$ git clone https://github.com/suurjaak/Skyperious
followed by
$ python Skyperious/skyperious/main.py
works.

**Comment by JPGlaser** [comment]
Currently, running the above suggestion by @qtlin on Fedora 22/24 does not yield a working installation (either through GitHub or the PIP installs). Any suggestions?

~ Joe G.

**Comment by suurjaak** [comment]
Closing this issue, as the program has become obsolete. But the latest version, Skyperious 3.6, should no longer have this crash.
