### ISSUE TITLE
Remove non-skype DBs

### ISSUE THREAD

**Issue by randomaccess3** [suurjaak/Skyperious#47]
Would be good if when you run the "Import from Folder" there was an option to only import main.db's

**Comment by suurjaak** [comment]
In principle, this could be a useful feature.. Do you have a specific idea on how exactly this should look in the interface? As in, have a separate button to import only main.db-s, or an additional popup menu like on the "Export messages" button, or an additional confirmation popup after choosing the folder, or ..?

**Comment by randomaccess3** [comment]
Maybe a checkbox when you select the folder saying "only import main.db's" when you select the base folder

**Comment by malitech** [comment]
Skyperious is able to read some other db-s too. So, I don't recommend forcing only main.db-s to be opened. Or at least if other db-s are dragged into skyperious, let it process it just like now.

**Comment by randomaccess3** [comment]
Yeah it's good for reading other databases; I just would like a way to tell it to ignore everything other than main.db; not force it to always ignore everything other than main.db

**Comment by suurjaak** [comment]
I'm a bit stumped as to how exactly implement this, without additional popups, or multiple buttons with very similar functionality. Since the folder selection dialog is an OS standard dialog, it is not easily possible to have an additional checkbox in the dialog itself.

Or what about having a button on the start page "Remove non-Skype", which would retain only Skype databases in the main list?

**Comment by randomaccess3** [comment]
What about a way to use ctrl or shift to select the databases and then you can just keep the remove button as is? Slightly more manual process but would work

**Comment by malitech** [comment]
The app can just read files named "main.db" or main+suffix, for example main1, main(old)...etc. Or your suggestion "Remove non-Skype" would be just fine.

Please don't remove any existing functions.
