### ISSUE TITLE
Export statistics for chat as HTML

### ISSUE THREAD

**Issue by asmaier** [suurjaak/Skyperious#52]
Hi,
it would be nice, if it would be possible to export the statistics about a chat in the GUI (Message counts, Word cloud, Emoticons statistics) also as HTML or in another machine readable format.

**Comment by asmaier** [comment]
Sorry, I found the statistics now in the HTML output. Just click on the link at the top of the HTML output.

**Comment by suurjaak** [comment]
Indeed :) Not quite machine-readable, but available in HTML export.
