### ISSUE TITLE
headless version

### ISSUE THREAD

**Issue by glensc** [suurjaak/Skyperious#53]
hi

most of the skyperious stability issues are caused (at least for me) due wxWindows issues.

right now i'm getting:

```
➔ skyperious
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).
Aborted (core dumped)
```

so, maybe have some headless version, as what i want to do is to do conversion from one format to another anyway. i'm currently interested of [csv export to import to slack](https://get.slack.help/hc/en-us/articles/201748703-Importing-message-history)

**Comment by santeriv** [comment]
+1Are you @glensc interested just exporting the data in csv format.
I am interested of letting skype run for user and finding from better app than skype discussions with search term.

**Comment by glensc** [comment]
yes, csv export only, but i found different solution: https://github.com/glensc/skype-logs

**Comment by suurjaak** [comment]
Actually, Skyperious has a [command-line interface](http://suurjaak.github.io/Skyperious/help.html#commandline).

(Note: the current PyPi version is not fully wx-independent, but github trunk is.)

**Comment by santeriv** [comment]
Thanks @suurjaak REST would have been a bit overkill for "mydata"-approach even having a JavaScript web app based on electron.js. I should be able to do a skyperious CLI search in node.js context anyway. Thanks.

**Comment by glensc** [comment]
if you mean 878957fa8e69b21b9c5465458a896a7008e0bcdc

then it still loads "wx" and in my case ... crashes! so it's not wx-less!

**Comment by suurjaak** [comment]
Closing this issue, as the program has become obsolete.

**Comment by glensc** [comment]
yes. thanks. your project has been very useful for finding the constant values :)

- https://github.com/edderrd/skype-logs/blob/5390942b1ca5897ec3a134e6352ffee86885a909/src/SkypeDatabase.php#L12

**Comment by suurjaak** [comment]
I've brought Skyperious back from obsolescence, as I've found a way to download new messages from Skype online service. 

Is this issue still relevant?
