### ISSUE TITLE
error when attempting to login with live: address

### ISSUE THREAD

**Issue by MyPod-zz** [suurjaak/Skyperious#54]
live:ID addresses aren't handled properly and login fails with http://puu.sh/ndHbp/fe9f64429d.png
In this case it should be required the user to input the proper mail address they registered with, along with the password.

edit:
the live ID is obtained by using the mail address truncated at @ 
The error happens when trying to export the database to html with embedded pictures.

**Comment by suurjaak** [comment]
Closing the issue, as the Skype login is no longer available.

**Comment by suurjaak** [comment]
FYI: I have released a new version of Skyperious, v4.0, where login is possible again.
