### ISSUE TITLE
no changes after merge

### ISSUE THREAD

**Issue by crowincage** [suurjaak/Skyperious#55]
Hej and first of all - thx for your work!

Today I've installed Skyperious via pip on my mac (OSX 10.11) to merge skype history from my old laptop to a new one. Merging in Skyperious seems to work without trouble - also the file size seems to fit after. But when I start Skype again (of course did merging with Skype NOT running) I can only see the history as it was before - not a single message from my older history.
Opened Skyperious again to browse the merged db file and there I could see the older messages - but no display in Skype.

Did I miss something?
I'm using latest Skype v7.28

thx for helping
crow

**Comment by ooshann** [comment]
hi,
have you been able to solve this issue?
I have the same problem and I appreciate if anyone can help.

thanks

**Comment by rafalh** [comment]
Hey, I had the same issue and managed to fix it by running following SQL query:
`UPDATE Messages SET timestamp_ms=timestamp*1000 WHERE timestamp_ms IS NULL`
@suurjaak

**Comment by Yunimori** [comment]
Rafalh, how does one run the SQL query? In the python console?

**Comment by Yunimori** [comment]
@rafalh This also doesn't seem to work for me. It says that there's no such line as timestamp_ms when I try to run it from the SQL window. I'm having the same issue as everyone above, database updated and can see the additional messages in Skyperious, but not in Skype itself. It won't go back more than a month, and I need it to go back to at least 2015.  Help?

**Comment by suurjaak** [comment]
Closing this issue, as Skype has completely reworked its chat history and it's no longer available to third-party programs like Skyperious.
