### ISSUE TITLE
Remove "Press Enter to exit" in CLI

### ISSUE THREAD

**Issue by x2souffxw** [suurjaak/Skyperious#56]
Hello.
I am trying to automate exporting of Skype messages using Windows Task Scheduler. My aim is to have daily backups of important chat messages.
Unfortunately my .bat file never ends the script properly because Skyperious expects an user to press enter on exit.
I would like to remove that "press key" functionality and recompile Skyperious, I already downloaded the source code. I found some functionality that is in main.py source file and tried to comment it out. Then I rebuilt the package with Pyinstaller explorer but CLI is still asking for Enter key. I know this is not a very professional way but I have never touched Python before and I was looking for a quick solution.

**Comment by suurjaak** [comment]
Closing this issue, as Skyperious has become obsolete - Skype no longer has chat history available for third-party programs, so daily backups are impossible.

**Comment by suurjaak** [comment]
FYI: I have released a new version of Skyperious, v4.0, capable of downloading chat history from Skype online service. This version has no "Press Enter" at the end of a command-line operation, instead it keeps the window open for a minute when all is done.
