### ISSUE TITLE
There is no 'skyperious' to run after installing

### ISSUE THREAD

**Issue by onetigr** [suurjaak/Skyperious#58]
There is no 'skyperious' to run after installing, installed with pip on macports.

**Comment by suurjaak** [comment]
Closing this issue for now, since Skyperious has become obsolete, as Skype no longer has chat history available to third-party programs. 

If you still want to use it on Mac, reopen the issue and let me know.

**Comment by suurjaak** [comment]
I've brought Skyperious back from obsolescence with the latest version 4.0. Is this issue still relevant?
