### ISSUE TITLE
No redirect form detected on token page

### ISSUE THREAD

**Issue by nirkons** [suurjaak/Skyperious#60]
Hi,
this error occurs when exporting a chat and selecting Yes to download the chat images from Skype web as well.

It seems like Skype have changed their login page and merged it with the Microsoft live account signup page, I tried fixing the problem myself without success, is there any chance that this can be fixed?

thanks!

**Comment by peterpeterpeter1** [comment]
Unfortunately i have the same problem. I really need to export one big conversation with images inside and have the same issue with login. There is some way to fix this?

**Comment by jordanwilliams1** [comment]
^^^^^^^^^^^^^^^

**Comment by suurjaak** [comment]
As the Skype login page is no longer available, the latest version, Skyperious 3.6, no longer has this login option.

**Comment by suurjaak** [comment]
FYI: I have released a new version of Skyperious, v4.0, that is able to download shared images again.
