### ISSUE TITLE
Error on search

### ISSUE THREAD

**Issue by excal789** [suurjaak/Skyperious#62]
Skyperious 3.5
Skype 7.31.80.104
Windows 10 x64

After accepting an invitation to try the new Skype Universal App for Windows 10 and then realizing the new app created a brand new database in my user folder, I used the merge feature to merge the last few days of messages back into the main database and uninstalled the new app.

All was well until I searched for a certain keyword that must have hit a problem message:

Error searching C:\Users\[user]\AppData\Roaming\Skype\[user]\main.db:
Traceback (most recent call last):
File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\workers", line 266, in run
File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\third_party.step", line 61, in expand
File "<string>", line 19, in <module>
TypeError: 'NoneType' object has no attribute '__getitem__'

Logged SQL was: SQL: SELECT m.* FROM messages m WHERE m.type IN (2, 4, 8, 9, 10, 12, 13, 30, 39, 50, 51, 53, 60, 61, 63, 64, 68, 70, 201) AND ((m.body_xml LIKE :body_like0 AND m.body_xml LIKE :body_like1 AND m.body_xml LIKE :body_like2)) ORDER BY m.timestamp DESC
		Parameters: {'body_like0': u'%last%', 'body_like1': u'%modified%', 'body_like2': u'%date%'}

Thanks...

**Comment by suurjaak** [comment]
Should be fixed in the latest version, 3.6.
