### ISSUE TITLE
[how-to] change font-size of chats

### ISSUE THREAD

**Issue by kramred** [suurjaak/Skyperious#63]
For anyone looking how to change the font-size of the chat history:
The setting is in `conf.py` line 200/201 and called `HistoryFontSize`:
```ini
"""Font size in chat history."""
HistoryFontSize = 8
```
Further, it seems you can zoom in/out, i.e. increase/decrease the font-size by `cmd`+scroll up/down on the mouse/trackpad (this is for macOS, for other OS it is probably `ctrl`+scroll up/down)

**Comment by suurjaak** [comment]
HistoryFontSize is also now a configurable setting in File -> Advanced options.
