### ISSUE TITLE
DB file size remains the same after merging

### ISSUE THREAD

**Issue by James2516** [suurjaak/Skyperious#65]
My .db file size is currently at 125152KB which seems to be the cap?
When i try to merge another db file into it (with some new rows added), the size remains exactly the same.

**Comment by suurjaak** [comment]
There is no cap on the database size. If the file size does not change after merging, then that's because SQLite does not repack the database unless it has to. 

You can execute `VACUUM` in SQL window before merging, to get the file size down to exactly what it should be.
