### ISSUE TITLE
Can't find any chats in database main.db

### ISSUE THREAD

**Issue by arun-gurung** [suurjaak/Skyperious#67]
I got Skyperious running. I open the file /home/arun-g/.config/skypeforlinux/skylib/weseefromage/main.db

But there are no chats shown. I have at least one long chat inside Skype but Skyperious shows no chats and nothing at all to show.

**Comment by Camyza** [comment]
Have this problem too.

**Comment by arun-gurung** [comment]
If I transfer over my profile and main.db from my Android mobile, then Skyperious is able to read the database and find the chats. On Linux, the main.db is located at /home/arun-g/.config/skypeforlinux/skylib/weseefromage/main.db and it is empty in Skyperious.

I am using Skype Preview version 8.11.76.8.

**Comment by bernd-wechner** [comment]
I upgraded Win7 to to Win10 now with Skype 12.9 and while Skyperious can see main.db, clearly something with Skype has changed because ti has no history post dating my upgrade in it. I'd guess the WIn10 Skype app is using a different database. Hmmmm ... how to find it?

**Comment by arun-gurung** [comment]
Skype for Linux version 8.52.0.138 has changed the filename from main.db to Databases.db. It's still empty in Skyperious. Conclusion is that chats are not stored locally at all, but only in the cloud.

As last time, I still have to root my Android and copy over the chat database in order to read it in Skyperious. Sorry that my shiny new mobile is impossible to root at this time. :-(

**Comment by arun-gurung** [comment]
I forgot to say I own a Windows 10 PC, so the problem can be solved if I can find the chat database there. But still not happy with Skype, because I heard they store the chats in the cloud for max two months, or something. Ergo, since I have Skype only on Linux and Android, then I have no original main.db where everything should have been stored to begin with. :-(

*lol*

**Comment by suurjaak** [comment]
FYI: I have released a new version of Skyperious, v4.0, that can download new messages from Skype online service and save them in main.db, although Skype itself is no longer using the main.db file.
