### ISSUE TITLE
Exporting skype chat format issues

### ISSUE THREAD

**Issue by IndustrialOne** [suurjaak/Skyperious#68]
When exporting skype chats, they should look like they do when Skype does it.

Skyperious does it this way:

10:57 Speedy X:
but at least 1/3 of the buds are covered in purple

16:48 Speedy X:
yo we should try playing some mario party today or tomorrow

When it should look like:

[1/23/2016 10:57:57 AM] Speedy X: but at least 1/3 of the buds are covered in purple
[1/23/2016 4:48:23 PM] Speedy X: yo we should try playing some mario party today or tomorrow

How do I make it most like the latter? I guess I can fix it with regex but I need the hh:mm:ss right now. Skyperious only exports hours and minutes but not the seconds.

**Comment by suurjaak** [comment]
Text mode export is deliberately limited. Other export types like HTML or XLSX have more data, including the precise timestamp.

**Comment by IndustrialOne** [comment]
The precise timestamp can just as easily be in text.
[6/30/2015 6:17:58 PM] John: yo
That's how it should be exported, the exact way Skype itself does it.

________________________________

**Comment by suurjaak** [comment]
What is your use-case, that you need text export to have the complete timestamp for all messages?

**Comment by IndustrialOne** [comment]
To archive my conversations in the same way Skype normally does it when I copy from it and paste into notepad to save as a txt file. Except Skype is not displaying the entire chat history for some reason despite it being right there in the main.db file, which forces me to use third party programs like yours to export it since Skype is failing to load the entire chat history.

________________________________

**Comment by suurjaak** [comment]
The reason Skype no longer shows you what's in main.db, is because it's no longer using main.db. Starting from version 8, Skype is not peer-to-peer any more, and keeps all its history in central servers. 

But it's curious you say that copy-paste from Skype gives you format like "[6/30/2015 6:17:58 PM] John: yo". When I try it, it gives me exactly what Skyperious is exporting:

    18:17 John
    yo

Maybe it depends on the platform - this is on Windows.

**Comment by IndustrialOne** [comment]
Well that sucks balls, I didn't even know that. I gotta admit, I was always skeptical of how P2P Skype really was.

I tried copy-pasting right now with this latest version of Skype and I got the same format as you, so it seems this was how it used to work. Nevertheless, I'd like to keep my format of the archives consistent so I would appreciate if your app made this format an option.

________________________________

**Comment by suurjaak** [comment]
I don't know if I want to introduce configurability for such a corner case. In a decade of existence of this program, this is the first time a user has wished for such an option. 

There is a possible workaround: open the Python console in Skyperious (Help -> Show Python console) and paste this:

```python

templates.CHAT_MESSAGES_TXT = """<%
from skyperious import skypedata
from skyperious.lib import util

previous_day = None
%>
%for m in messages:
%if m["datetime"].date() != previous_day:
<%
# Day has changed: insert a date header
day = m["datetime"].date()
weekday, weekdate = util.get_locale_day_date(day)
previous_day = m["datetime"].date()
%>

{{weekday}}, {{weekdate}}
----------------------------------------

%endif
%if skypedata.MESSAGE_TYPE_INFO == m["type"]:
[{{m["datetime"].strftime("%#m/%#d/%Y %#H:%M:%S")}}] {{db.get_author_name(m)}} {{parser.parse(m, output={"format": "text", "wrap": True})}}
%else:
[{{m["datetime"].strftime("%#m/%#d/%Y %#H:%M:%S")}}] {{db.get_author_name(m)}}: {{parser.parse(m, output={"format": "text", "wrap": True})}}
%endif

%endfor
"""

```

You would need to paste this each time you open the program. Or use the source distribution and change the `skyperious\templates.py` file directly.
