### ISSUE TITLE
wx._core.PyNoAppError: The wx.App object must be created first!

### ISSUE THREAD

**Issue by CorneAussems** [suurjaak/Skyperious#70]
Hi I just installed it from both source code as well as pip but get the same message.

MacbooK-pRo:skyperious_3.5 corne$ sudo pip install skyperious
The directory '/Users/corne/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/corne/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting skyperious
  Downloading Skyperious-3.5-py2-none-any.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 1.0MB/s
Requirement already satisfied: python-dateutil in /Library/Python/2.7/site-packages (from skyperious)
Collecting XlsxWriter (from skyperious)
  Downloading XlsxWriter-1.0.2-py2.py3-none-any.whl (139kB)
    100% |████████████████████████████████| 143kB 3.9MB/s
Requirement already satisfied: pyparsing in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from skyperious)
Collecting Skype4Py (from skyperious)
  Downloading Skype4Py-1.0.35.zip (173kB)
    100% |████████████████████████████████| 174kB 4.4MB/s
Collecting BeautifulSoup4 (from skyperious)
  Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 5.0MB/s
Collecting Pillow (from skyperious)
  Downloading Pillow-5.0.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.5MB)
    100% |████████████████████████████████| 3.5MB 365kB/s
Requirement already satisfied: six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil->skyperious)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from Skype4Py->skyperious)
Installing collected packages: XlsxWriter, Skype4Py, BeautifulSoup4, Pillow, skyperious
  Running setup.py install for Skype4Py ... done
Successfully installed BeautifulSoup4-4.6.0 Pillow-5.0.0 Skype4Py-1.0.35 XlsxWriter-1.0.2 skyperious-3.5
MacbooK-pRo:skyperious_3.5 corne$ skyperious
/Library/Python/2.7/site-packages/skyperious/controls.py:2323: wxPyDeprecationWarning: Using deprecated class. Use Colour instead.
  SEARCH_NOMATCH_BGCOLOUR = wx.NamedColour("#FF6666")
Traceback (most recent call last):
  File "/usr/local/bin/skyperious", line 7, in <module>
    from skyperious.main import run
  File "/Library/Python/2.7/site-packages/skyperious/main.py", line 47, in <module>
    import export
  File "/Library/Python/2.7/site-packages/skyperious/export.py", line 34, in <module>
    import skypedata
  File "/Library/Python/2.7/site-packages/skyperious/skypedata.py", line 46, in <module>
    import support
  File "/Library/Python/2.7/site-packages/skyperious/support.py", line 30, in <module>
    import controls
  File "/Library/Python/2.7/site-packages/skyperious/controls.py", line 2283, in <module>
    class SearchableStyledTextCtrl(wx.PyPanel):
  File "/Library/Python/2.7/site-packages/skyperious/controls.py", line 2323, in SearchableStyledTextCtrl
    SEARCH_NOMATCH_BGCOLOUR = wx.NamedColour("#FF6666")
  File "/Library/Python/2.7/site-packages/wx/core.py", line 72, in __init__
    item.__init__(*args, **kw)
wx._core.PyNoAppError: The wx.App object must be created first!

Would be great if someone could help

**Comment by gustl85** [comment]
Hi,

which version of wxPython do you use?
Mine is running fine after downgrading to wxPython 3.x

**Comment by CorneAussems** [comment]
HI thanks for the suggestion, 

I had installed it through pip so 4.0.1 was installed.
But i can't seem to find how to install the 3.0.2 version though.
All pkg from https://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/ are saying it to be corrupted?!

**Comment by azizcodes** [comment]
I am having the same problem.
```
wx._core.PyNoAppError: The wx.App object must be created first!
```
Running wxPython==4.0.1. Earlier versions aren't available through pip.
```
Could not find a version that satisfies the requirement wxPython==2.9 (from versions: 4.0.0a1, 4.0.0a2, 4.0.0a3, 4.0.0b1, 4.0.0b2, 4.0.0, 4.0.1)
No matching distribution found for wxPython==2.9
```

**Comment by Gorbush** [comment]
Any progress on this?

**Comment by azizcodes** [comment]
Yes,

```
pip2 uninstall wxpython 
brew install wxpython
```

Then I was getting an error by just running `skyperious`.

```
AttributeError: 'module' object has no attribute 'xlsxwriter'
```
If you run
```
python2 /usr/local/lib/python2.7/site-packages/skyperious/main.py
```
The program starts.

I got a new problem though. The program doesn't recognize my databases.

Skype user: (not recognized as a Skype database)
Conversations: OperationalError: no such column: c.meta_topic

It can read some information about the database but doesn't show the conversations (if you go to the data tables, for example).

**Comment by suurjaak** [comment]
Closing the issue, as Skyperious has become obsolete.

**Comment by suurjaak** [comment]
Is this still an issue with the newest v4.0?
