### ISSUE TITLE
Please update emoticons

### ISSUE THREAD

**Issue by timeakesmarky** [suurjaak/Skyperious#72]
Can you please update skype emoticons? You can find the gifs here:
http://www.skaip.org/skype-emoticons

**Comment by suurjaak** [comment]
Since Skype chat history is no longer available to third-party programs, I have stopped development on Skyperious.

**Comment by suurjaak** [comment]
FYI: I have released a new version of Skyperious, v4.0, with support for a lot more emoticons.
