### ISSUE TITLE
Windows tries to export filenames with invalid characters

### ISSUE THREAD

**Issue by Simon818** [suurjaak/Skyperious#73]
I have a friend who somehow managed to insert a line break into her name. Exporting on Linux has always worked for me, but I tried it on Windows to save some time and it failed when it got to that one.
Thank you for maintaining this; it's extremely usefu for me and I've helped a number of other people use it to export their history.

**Comment by suurjaak** [comment]
The newest version, Skyperious 3.6, should no longer have this issue. Not that this program is much relevant any more, chat history is no longer available to third-party programs.
