### ISSUE TITLE
"No login form detected on start page"

### ISSUE THREAD

**Issue by JPUnD** [suurjaak/Skyperious#76]
I've ran into this error while recovering from an old (8 years old at least) database that i found in my old desktop.

All the messages are extracted just fine, but when logging in to retrieve the pictures, something goes wrong and this error shows up. I thing it's something to do with the fact that skype login has changed.

The version is the latest binary for windows download today (28-1-2020) - version 3.5 according to client.

**Comment by suurjaak** [comment]
Skype login for downloading shared pictures is not available any more. 

A new Skyperious version, 3.6, no longer has this download option.

**Comment by suurjaak** [comment]
FYI: I have released a new version of Skyperious, v4.0, where the login form and image download have been restored.
