### ISSUE TITLE
Skyperious - version 4.0.1 30.07.2020

### ISSUE THREAD

**Issue by JamesDandy** [suurjaak/Skyperious#77]
This new product worked great reading my older database but after logging in successfully to my online account and downloading the database, I received the following error when trying to read the chats:
> Error loading chat with xxx
> Traceback (most recent call last):
> Flie “gui.py”, line xxxx, in load_chat
> Flie “gui.py”, line xxxx, in Populate
> Flie “gui.py”, line xxxx, in RefreshMessages
> Flie “skypedata.py”, line xxxx, in parse
> Flie “skypedata.py”, line xxxx, in collect_message_stats
> TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

After receiving this error I deleted the database and tried to download it again but now I get the following error:
> Failed to log in as 'xxx':
> IOError: (13, Permission denied)

I am using correct login data and have tried multiple times.

**Comment by suurjaak** [comment]
Fixed in version 4.1, released today.
