### ISSUE TITLE
Can't login to Microsoft account - error 200

### ISSUE THREAD

**Issue by arun-gurung** [suurjaak/Skyperious#78]
A few days ago, everything worked. Now, Skyperious can't login, even if I use my email address or live-username. But I can still logout and login with Skype on Windows and on Linux. I have latest version 4.0.1.

![Capture](https://user-images.githubusercontent.com/28502386/90354769-86ae6800-e04a-11ea-9255-494e8eb98c06.PNG)

**Comment by arun-gurung** [comment]
Now it worked again. I am sure I wrote the correct password. Please disregard the issue.

**Comment by suurjaak** [comment]
Looks like the API login can sometimes fail for no discernible reason. A few other users have also reported the same problem. 

I should probably put in an informational message to that effect.

**Comment by arun-gurung** [comment]
It's me, again. Sorry to reopen the issue, but now the problem is back and persistent. I am getting to my tears, because I really want to use your great app.

**Comment by suurjaak** [comment]
Is the error still "That Microsoft account doesn't exist" or is it something else now? 

Is the result any different between logging in on the Online-page, and choosing "Create new database from Skype online" on the initial program screen?

**Comment by arun-gurung** [comment]
It's the same error 200 this Microsoft account doesn't exist.

It's the same result whether I try to log in anywhere.

**Comment by arun-gurung** [comment]
FYI: I was able to log in and download my chats now again, but the problem is just coming and going.

**Comment by suurjaak** [comment]
The thing is, this login functionality is provided by a third-party library (https://github.com/Terrance/SkPy), so there is little I can do about the problems it encounters. 

Out of curiosity:

- do you have linked Skype and Microsoft accounts? 
- do you have two-factor authentication enabled in your account?
- do you experience problems logging in at https://web.skype.com?

**Comment by timea-techgirl** [comment]
@suurjaak Interesting... I logged in normally and my authenticator got a notification to approve or deny but skyperious doesn't wait for it as it doesn't know how and gives an error.

Same error with app password but no authenticator notification while logging in with app password.

Turning off two step verification, I get "Failed to retrieve t field...." error.

**Comment by suurjaak** [comment]
I found a solution that worked for my account - making an e-mail the primary alias of the account (simply enabling Outlook did the trick). After this, login works with both skypename and e-mail. 

App passwords made no difference one way or the other.

**Comment by timea-techgirl** [comment]
My email is the primary alias. What do you mean by enabling outlook?

**Comment by suurjaak** [comment]
> What do you mean by enabling outlook?

At account.live.com, going to "Services & subscriptions" and then clicking "Use Outlook.com for free". After logging in to outlook.live.com, login in Skyperious started working for me.

**Comment by timea-techgirl** [comment]
I see. Not working for me.

**Comment by suurjaak** [comment]
I found this solution at EionRobb/skype4pidgin#656. 

Which error are you getting now? Does disabling two-factor authentication make any difference?

**Comment by timea-techgirl** [comment]
Same t field error
No

**Comment by timea-techgirl** [comment]
I remember having google play store errors whenever I flashed a ROM and tried to sign in to my google account.
None of the solutions on the internet had worked. I finally fixed the issue by going to my google account and clicking "This was me" button in the recent login activity and the play store would work immediately. I thought Microsoft may have something similar and did a search. I found this:

> 1. Go to account.live.com/activity and sign in using the email address and password of the affected account.
> 
> 2. Under Recent activity find the Session Type event that matches the most recent time you received the connection error and click to expand it.
> 
> 3. Select This was me to let the system know you authorize the IMAP connection.

But only thing is, there is no "This was me" button like Google has.

**Comment by suurjaak** [comment]
What about if you re-verify your account from the "Secure your account" link under a Recent activity item?

**Comment by timea-techgirl** [comment]
It just says thanks for letting us know.

**Comment by suurjaak** [comment]
Released a new version, Skyperious v4.2, with an updated Skype API that should clear login errors for some accounts at least. 

Closing this issue for now.
