### ISSUE TITLE
Can't export images with HTML

### ISSUE THREAD

**Issue by arun-gurung** [suurjaak/Skyperious#79]
It's me, again. I'm trying to export a chat as HTML, but the images are not included but I get just links to skype.com. Same thing with exporting to Excel.

**Comment by suurjaak** [comment]
The images are downloaded via Skype login. If the login fails (as it can do intermittently), Skyperious falls back to the original message content, which is a link to skype.com. 

You can see in the log window (Help -> Show log window) whether the login failed.

**Comment by suurjaak** [comment]
On further investigation, this is indeed a bug in Skyperious. The auto-login done during export is faulty. 

Thank you for reporting this. Will be fixed in the next release. In the meantime, log in on the Online-page before running export.

**Comment by arun-gurung** [comment]
I'll try that.

Thank you.

**Comment by suurjaak** [comment]
Problem fixed in the freshly released v4.2.
