### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by timea-techgirl** [suurjaak/Skyperious#81]
Is it feasible to add a dark chat history export option?
Thanks!

**Comment by suurjaak** [comment]
I suppose there could be a toggle on the exported HTML page to switch to dark mode. 

With a result something along the lines of: 
![image](https://user-images.githubusercontent.com/719382/91657402-509cc980-eac9-11ea-832a-6ebc3f087021.png)

However, as you can see, emoticons are not going to look very nice, as they're simple GIFs. Skype itself is using APNGs internally, I think, as those support gradual transparency and can thus blend into any background. But they've not been publicly available.

**Comment by timea-techgirl** [comment]
Oh, that's not an issue. Wow, this looks awesome and saves eyes. Toggle would be perfect. 💯

I've previously seen this emoticon issue somewhere. Oh, here it is:
https://github.com/m4heshd/whatsapp-desktop-dark/issues/6

But it may be a lot of work, so it can be left as it is.

**Comment by suurjaak** [comment]
Available now in the latest version, 4.3.
