### ISSUE TITLE
SkypeAuthException: (wsse:FailedAuthentication - Authentication Failure, <Response [200]>)

### ISSUE THREAD

**Issue by rpodric** [suurjaak/Skyperious#83]
Hi. I hadn't updated Skyperious in the modern era so was very happy to see it's being updated again, particularly with the ability to interface with the cloud. I installed 4.2.

I read the information under the login area about it being unreliable and not for all accounts, but I thought I'd post this here in the hope that we narrow down the account types for which it will not work.

Mine is an old-school one, going back at least 10 years, and is _not_ linked to MSA. I login to Skype with just a normal username, like (not the real one): billg.

**SELECT skypename, signin_name, liveid_membername, msa_pmn FROM Accounts** returns (numbers adjusted):

Skypename: billg
Signin_name: billg
liveid_membername: cid-(3026756779212834888)@outlook.com
msa_pmn:

The error repeats every time over two days now. Thanks.

**Comment by suurjaak** [comment]
I also have an old-school Skype account, and was able to get login to work via https://github.com/suurjaak/Skyperious/issues/78#issuecomment-679159675

FYI: you can experiment with different login names yourself:

- open a database in Skyperious
- open the Python console (menu Help -> Show Python console)
- run `db.live.login("username", "password")` in the console

**Comment by rpodric** [comment]
I'll check into the email trick mentioned in that other post, but running that command leads to the same error as above, except this time right in that console after this is returned:

```
  File "<input>", line 1, in <module>
  File "live.py", line 104, in login
  File "site-packages\skpy\main.py", line 69, in __init__
  File "site-packages\skpy\conn.py", line 266, in getSkypeToken
  File "site-packages\skpy\conn.py", line 368, in liveLogin
  File "site-packages\skpy\conn.py", line 655, in auth
  File "site-packages\skpy\conn.py", line 674, in getSecToken
```

**Comment by rpodric** [comment]
I just wanted to write back (in advance of closing this thread--I didn't realize that it was still open) to add some more info to this situation. You said:

"At account.live.com, going to "Services & subscriptions" and then clicking "Use Outlook.com for free". After logging in to outlook.live.com, login in Skyperious started working for me."

That's true, but what happens after you click "Use Outlook.com for free" is interesting. When you go to login with your normal Skype U/P (let's say: username/password), it comes back and requests that you add an email to the account, which it says is going to be an alias. Every Skype account already has an email address associated with it, so this is something else. I chose to let it create one, picking username_s@outlook.com, let's say, and at that point it logged me into Outlook.

That didn't seem to affect Skype in any visible way: you can still login with username and all is the same as before. The difference is that when you now attempt to do an online login with Skyperious (still only using username, not the alias, though that might also work), it actually works.

The email that I received about the change read as follows, suggesting that it's all about the Microsoft account. It's unclear what doing this actually matters, but clearly it does. And perhaps newer accounts don't need to do this.

Your Microsoft account has been renamed. We just wanted to check with you that it's okay.
     -  Old account name: username
     -  New account name: username_s@outlook.com

**Comment by suurjaak** [comment]
Thank you, this information can be a handy reference to point other users to.  

Closing this issue for now.
