### ISSUE TITLE
so is skyperious working yet with skype 8.x?

### ISSUE THREAD

**Issue by 4evermaat** [suurjaak/Skyperious#87]
if so, can someone explain briefly how it now works with skype 8.x?  
including working with various media files/attachments in conversation.  

And can it stay running in the background with/without skype 8 client running and just keep local database of account conversations?

**Comment by suurjaak** [comment]
Skyperious does work with Skype 8, but not how it did before, as Skype is no longer using main.db files. 

Skyperious can download messages from Skype online API, and merge them into an existing older main.db or a blank new main.db file. So yes, you can still use it as a way to keep all your Skype history in one local place, but none of it affects what the official Skype client does, whether the client is running or not. 

When doing HTML export of chat history, Skyperious can download the shared images as well, and either embed them directly in the exported HTML file or store them in a subfolder.

**Comment by 4evermaat** [comment]
>  Skyperious can download messages from Skype online API, and merge them into an existing older main.db or a blank new main.db file. So yes, you can still use it as a way to keep all your Skype history in one local place, but none of it affects what the official Skype client does, whether the client is running or not.

> When doing HTML export of chat history, Skyperious can download the shared images as well, and either embed them directly in the exported HTML file or store them in a subfolder. 

Can this "full" backup process be automated? 

E.g. Download and merge all that is available with local command line, i could run windows task scheduler to do this daily to always have a local copy of chat history with media. And then i could further back that up as needed.

**Comment by suurjaak** [comment]
Yes, it can be automated: https://suurjaak.github.io/Skyperious/help.html#sync
