### ISSUE TITLE
can I use skyperious to take a .tar file from Skype, and make an html with images in-line with the chat history?

### ISSUE THREAD

**Issue by birdridge** [suurjaak/Skyperious#88]
Hello,

Thank your all your work. Skyperious is very useful for me to look up old chat history, if there is something I want to remember that I cannot find using the skype application, whether it is some important information or a nice memory.

I have a skype history with my partner and we want to see if there's a way using skyperious, to start with my .tar skype export file (which includes a messages.json and  provided by skype, and produce a html file or other export file which has the images in line with the text, as does the original skype interface. That would make it like reading our original chat. 

Currently, I have only been able to get it with the links to the web to the images (and the links do not work too well, I have to change the syntax to get it to open, but at least it is a start towards what I am looking for).

**Comment by suurjaak** [comment]
Yes, this is possible. You have to enter your Skype account password on the Online-page in Skyperious, log in, and then HTML export should contain the images in-line, as Skyperious can now log in to the online account and retrieve the images. 

By the way, what change are you making to the image links to get them open?

**Comment by birdridge** [comment]
Thank you, I have been able to make the export. I had tried a couple months ago and had trouble. I found out that by changing my primary skype alias to an email from a phone number, then I could sign in and skyperious worked as desinged. Awesome!

https://support.microsoft.com/en-us/account-billing/change-the-email-address-or-phone-number-for-your-microsoft-account-761a662d-8032-88f4-03f3-c9ba8ba0e00b



Here is how I got the images to open using the links provided by skype export:
this link works, I can check it from my web skype login, clicking a photo and selecting to open it in a new tab:
https://wus1-api.asm.skype.com/v1/objects/0-wus-d9-ff703525909fc2003f41e660150745bc/views/imgpsh_fullsize_anim 




This is the link provided in skype's export which does not work:
To view this shared photo, go to: https://login.skype.com/login/sso?go=xmmfallback?pic=0-wus-d9-ff703525909fc2003f41e660150745bc
-----

I  can get it to work by taking the string after pic= and plugging it into the XXXXX space from this link that comes from opening a photo in a new tab.

https://wus1-api.asm.skype.com/v1/objects/XXXXX/views/imgpsh_fullsize_anim

Making the working link to a photo (for when I am logged into skype online) of:
https://wus1-api.asm.skype.com/v1/objects/0-wus-d9-ff703525909fc2003f41e660150745bc/views/imgpsh_fullsize_anim

**Comment by suurjaak** [comment]
Thank you, this is very helpful. 

Some months ago Microsoft did some major changes in their API, as a result many third-party tools stopped working and had to be updated. But not even their own links work any more - later messages still have this "login.skype.com/login/sso" thingy, and opening it yields "Page not found". 

I should release an update that has proper working links. Pity that there doesn't seem to be a link that would support login also.
