### ISSUE TITLE
Skyperios does not download full available history

### ISSUE THREAD

**Issue by Alessar** [suurjaak/Skyperious#91]
Let's imagine that account was in one group for some time. At one day, it was removed from that group, and after several days it was added again into that group. Skype shows that it was the same group as it was earlier. And moreover, skype shows full history before the removing time (and after the adding time). So Skype hides history when the user was out of the group (- it is expected).

Opening `Skyperious`, entering into login account and synchronizing history (full or only specified group).
Expected that `Skyperious` download full available history of the group (The same which can be available in skype).
Actual that `Skyperious` download the only history after the last adding the user into the group.

It will be good if `Skyperious` can download full available history of the group (if it is available for the user in Skype)

**Comment by suurjaak** [comment]
If you go to Skype's web interface, at https://web.skype.com/, can you see the full history available there? 

Because if not, then it's probably not available via Skype API, but might have been cached in the local Skype installation.

**Comment by Alessar** [comment]
Tested via WEB: I cannot see full history before removing date,
but I can see several messages before re-adding into the group.

If full history was cached on a local computer, can you provide any details where it was saved?
Obvious place `Messages` table in the `main.db` does not contain that full history.

**Comment by suurjaak** [comment]
> Tested via WEB: I cannot see full history before removing date

In that case, those messages are not available via the web API, and so Skyperious has no chance of retrieving them.

> but I can see several messages before re-adding into the group.

Hmm, and these messages were not shown in Skyperious? Now this may be something. Can you do the following:

- open the database in Skyperious
- log in to Skype on the Online-page
- open that one chat on the Chats-page
- select menu Help -> Show Python console
- in the Python console, execute `chatid = live.identity_to_id(page.chat["identity"])`
- execute `chat = db.live.skype.chats.chat(chatid)`
- execute `chat.getMsgs()` over and over again, until it starts returning an empty list

How far back do the last messages go?

> If full history was cached on a local computer, can you provide any details where it was saved? Obvious place Messages table in the main.db does not contain that full history.

Unfortunately, no. Skype no longer uses main.db at all, and nobody outside of Microsoft knows how or what they store anything locally. History is kept in the cloud, but obviously some of it must also be kept locally if the desktop application shows the previous messages and the web application doesn't.

**Comment by suurjaak** [comment]
@Alessar: any update on the last question?

**Comment by Alessar** [comment]
Testing on new local instance showed that previous history is not available, unfortunately.
So looks like history is kept on some local cache. And that's why `skyperios` cannot see it.

In any case, thanks for the discussion. And thanks for `skyperios` at all.

**Comment by suurjaak** [comment]
All right then. Unfortunate that the messages gone.

**Comment by suurjaak** [comment]
@Alessar the new v4.7 release is able to download more messages from online, you can try it and see if it's able to retrieve those lacking previously.
