### ISSUE TITLE
Error loading any chat (suddenly)

### ISSUE THREAD

**Issue by rpodric** [suurjaak/Skyperious#94]
This is a strange one. Skyperious v4.4 had been working just fine on Win10 Insider, but now when attempting to open any chat from either database:
https://i.imgur.com/Mnrnw4o.png

And v4.5 is the same, which I noticed was out.

I had been using Skyperious no more than one week before without incident. What changed on my end? The version of Windows is the one thing that I can think matters: Build 21322. The previous build (21318) did not show the issue.

I had a friend test on the same version of Windows with his completely separate Skyperious install, and he sees the same, which I think increases the likelihood that this is Windows but certainly doesn't prove it.

Could one of the dozen or so components used in Skyperious not like the current Windows build?

**Comment by raspberrysapphire** [comment]
Currently having the same issue with the exact same error message, but on Windows 10 Home, Version 1909, OS Build 18363.1379. Last time I used Skyperious was December 5th 2020, with version 4.3.1. I tried to use it again today, got this error, updated to 4.5, and continued to get the same error. Sorry that I can't provide more info or a better time frame, unfortunately, but I figured the input could be helpful. 

Here's a list of every update I've installed since November: 
https://i.imgur.com/G4quDJ9.jpg

**Comment by suurjaak** [comment]
Yep, I stumbled onto this bug myself two days ago, and have had reports coming in from other sources. There's a problem with recently introduced date arithmetic that expresses itself only during March, this is why it has suddenly started occurring. 

There's already a fix available, but I'm loathe to issue a public release before getting at least some testing on this. Can you try this attached setup: [skyperious_4.5.1.dev20_x64_setup.zip](https://github.com/suurjaak/Skyperious/files/6070253/skyperious_4.5.1.dev20_x64_setup.zip), and report whether there are any problems with it? 

Its total changes from the current v4.5 are:

- update existing contact information in database on live sync;
- added option to not overwrite contact information in database from live;
- sync older chats from live not just recent ones (issue #93);
- added option to not sync older chats from live;
- show `<pre>`-tag content in chat reader;
- show @-taggings in chat reader and style them bold in reader and HTML;
- ask for confirmation when exporting HTML with media in subfolder, but login unavailable for downloading media (issue #93).
- fixed error on creating chat date links during the month of March;
- fixed "Go to previous [period]" not working in chat history if history starts with previous period;
- fixed merge not showing correct diff in individual chats view;
- fixed duplicates in syncing bot contacts and messages from live (issue #93);
- fixed not retaining the order of command-line FILE arguments (issue #93);
- fixed displaying shared media with duplicate filenames in HTML export with subfolder (issue #93);
- add detected media type extension to shared media exported in HTML if lacking one (issue #93).

**Comment by rpodric** [comment]
That's good, since once he said that it happened on an old version of Windows too, what this could be was really narrowed, and time makes sense. I've installed the dev release and it's fine so far. Thanks.

**Comment by suurjaak** [comment]
The new released version 4.6 fixes the issue.
