### ISSUE TITLE
Virus detected by Kaspersky

### ISSUE THREAD

**Issue by windvane** [suurjaak/Skyperious#95]
Version: Skyperious 4.6
Anti-Virus software: Kaspersky
Virus/Threats Name: WORM.WIN32.CRIDEX

**Comment by suurjaak** [comment]
Thank you for reporting this. This is a perennial problem with packaged Python programs, that antivirals consider them malicious. 

I've contacted Kaspersky Labs about this, and they have now responded:

> Sorry, it was a false detection. It will be fixed.

But there are other engines reporting this file: 
https://www.virustotal.com/gui/file/b11c38efc483122663be94b1bf4dde5879b86bfa0b6af670faadafe496816884. I've reported the false positive to the other antivirals, hopefully they will clear them.

**Comment by suurjaak** [comment]
All false detections now clear at VirusTotal.
