### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by lockywolf** [suurjaak/Skyperious#96]
Hello, and thank you for the excellent tool!

Skype seems to be still very relevant in 2021 (especially with the rise of remote work).
However, Skyperious still relies on python2, which has been declared EOL in January 2021, and pip would likely soon decommission python2 support.

How hard would be to port Skyperious to Python 3.9?

**Comment by suurjaak** [comment]
Python 3 support now available, from version 5.0.
