### ISSUE TITLE
Be friendlier to non-terminals?

### ISSUE THREAD

**Issue by lockywolf** [suurjaak/Skyperious#97]
Skyperious displays a progress bar when run from console. A great thing for humans, but... not so great for running exports from cron, because each progress bar update ends up in the output file or the email from cron.

Would it be possible to add an option to make output "plain text" in case stdout is a non-terminal?

**Comment by suurjaak** [comment]
Good point. 

Should add a flag e.g. `--no-progress` or `--plain-text`, to skip outputting textual progress bars.

**Comment by suurjaak** [comment]
Added `--no-terminal` argument for the command-line interface. 

Available in the new v4.7 release.
