### ISSUE TITLE
Skyperious 4.7 can't find all chats

### ISSUE THREAD

**Issue by arun-gurung** [suurjaak/Skyperious#99]
I upgraded to 4.7 and now, it can only find a few chats. Not my main chat with lots of messages that I want to export.

**Comment by suurjaak** [comment]
Can you describe the problem in a bit more detail? Where does it not find the chat? In an existing database? During the online sync?

**Comment by arun-gurung** [comment]
I can make a new database by logging into Skype. It scans the chats and populates the chat list, but it displays only three chats.

**Comment by suurjaak** [comment]
Can you do the following:

- open a database in Skyperious, log in to Skype on the Online-page
- open the Python console (menu Help -> Show Python console)
- in the console, execute the following:

```python
cc = {}
cc.update(db.live.skype.chats.recent())
len(cc)
```

Does it print more than three? 

And if yes, what is the result if you execute:

```python
for name, chat in cc.items():
    print name, len(chat.getMsgs())
```

**Comment by arun-gurung** [comment]
Now I created a new database and it shows four chats (that I don´t  know about), but not my main chats.

If I execute your commands in the Python console, I get no feedback at all.

**Comment by suurjaak** [comment]
Sorry, should have specified: execute the commands line-by-line.

**Comment by arun-gurung** [comment]
I did and I get returned "0".

**Comment by suurjaak** [comment]
Well, that is the source where Skyperious gets conversation history from. If it's returning nothing, then there is little to be done. 

Are you sure you are using the correct username? 

You said this problem arose when you upgraded to v4.7. Is the outcome different with v4.6?

**Comment by arun-gurung** [comment]
I am sure I use the correct username.

I tried v4.6 down to 4.4 and they won't list any chats at all. I went back to 4.7 and it lists four chats, but not my main chat.

**Comment by suurjaak** [comment]
So, has the online sync ever worked for your account in any version?

**Comment by arun-gurung** [comment]
Yes, the last time it worked was with version 4.5.1 or something like that. I don't remember right now, but I upgraded to 4.7. I can try to downgrade further than 4.4.

**Comment by arun-gurung** [comment]
Now I tried with 4.2 and 4.01 but no luck. I have a Windows PC somewhere else and I will try from there, but I would prefer to have it on my Linux laptop.

**Comment by arun-gurung** [comment]
I forgot to tell you that I get a warning on the upstart, it says: Cannot set locale to language "English (U.S.)". But it's just a warning and if I try the Python console, it says the locale is set to "UTF-8".

**Comment by suurjaak** [comment]
The locale warning is interesting. Is it a popup warning? Is there more information about it in the log (menu Help -> Show log window)?

**Comment by arun-gurung** [comment]
It's a popup warning at application start. No info in the log window.

**Comment by suurjaak** [comment]
Any luck on the Windows machine? Although the operating system should make no difference.

**Comment by arun-gurung** [comment]
Yeah, I will report later. The Windows machine is another place.

**Comment by arun-gurung** [comment]
On Windows, it can find my main chat and I can export as normal. Everything looks correct.

**Comment by suurjaak** [comment]
Now that is bizarre.. The operating system should really make no difference, and it works the same for me on Linux as on Windows. 

What is the precise version of Linux that you're running? And how are you launching the program? 

And what is the output of running `python -m pip freeze` in a terminal (or `python2 -m pip freeze`)?

**Comment by arun-gurung** [comment]
I'm running Manjaro v. 21.0.6 kernel 5.10.41-1.

alabaster==0.7.12
apipkg==1.5
appdirs==1.4.4
atomicwrites==1.4.0
attrs==21.2.0
Babel==2.9.0
backports.functools-lru-cache==1.6.4
beautifulsoup4==4.9.3
chardet==4.0.0
configparser==4.0.2
contextlib2==0.6.0.post1
css-parser==1.0.4
cssselect==1.1.0
dnspython==1.16.0
docutils==0.16
enum34==1.1.9
feedparser==5.2.1
freezegun==0.3.15
funcsigs==1.0.2
html2text==2019.8.11
html5-parser==0.4.9
html5lib==1.1
idna==2.10
imagesize==1.2.0
importlib-metadata==2.1.1
iniconfig==1.1.1
Jinja2==2.11.3
lxml==4.6.2
Markdown==3.1.1
MarkupSafe==1.1.1
mechanize==0.4.5
more-itertools==5.0.0
msgpack==0.6.2
netifaces==0.10.9
numpy==1.16.6
ordered-set==3.1.1
packaging==20.9
pathlib2==2.3.5
Pillow==6.2.1
pluggy==0.13.1
psutil==5.8.0
py==1.10.0
pyalsaaudio==0.9.0
pycairo==1.18.2
Pygments==2.5.2
PyGObject==3.36.1
pyparsing==2.4.7
PyQt5==5.15.0
PyQt5-sip==4.19.24
PyQtWebEngine==5.15.0
pytest==4.6.11
pytest-runner==5.2
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
scandir==1.10.0
six==1.16.0
SkPy==0.10
snowballstemmer==2.0.0
soupsieve==1.9.6
Sphinx==1.8.5
sphinxcontrib-websupport==1.1.2
typing==3.10.0.0
unrardll==0.1.4
urllib3==1.26.5
wcwidth==0.2.5
webencodings==0.5.1
wxPython==4.1.0
XlsxWriter==1.2.8
zipp==1.1.1

**Comment by suurjaak** [comment]
Can you try to upgrade skpy to the latest version? E.g. `python2.7 -m pip install skpy --upgrade`. Does that make a difference?

**Comment by arun-gurung** [comment]
Thanks, but no difference.

**Comment by suurjaak** [comment]
I set up a Manjaro installation myself, and installed and ran Skyperious there - syncing from online worked for me, and found everything. So there's probably something off with your system. 

What happens if you try to run the sync using the command-line interface? https://suurjaak.github.io/Skyperious/help.html#sync

**Comment by arun-gurung** [comment]
Thanks for your efforts. I have decided to reinstall my system, because there have been other errors as well.

I will last try to sync from the command line and report back to you.

**Comment by arun-gurung** [comment]
Now I tried the command line and same result, it finds four empty chats but not my main chat.

**Comment by suurjaak** [comment]
Please, do report back when you've reinstalled your system and retried the online sync. 

Closing the issue for now.

**Comment by arun-gurung** [comment]
I have reinstalled my system and I installed Python 2 and wxWidgets, but the furthest I get now is missing module "adv".

[arun-g@macbook-air skyperious_4.7]$ python2 -m skyperious
/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/arun-g/.local/skyperious_4.7/skyperious/__main__.py", line 2, in <module>
    from . import main
  File "skyperious/main.py", line 52, in <module>
    from . import export
  File "skyperious/export.py", line 36, in <module>
    from . import guibase
  File "skyperious/guibase.py", line 31, in <module>
    from . lib.controls import ColourManager, KEYS
  File "skyperious/lib/controls.py", line 98, in <module>
    import wx.adv
ImportError: No module named adv

**Comment by suurjaak** [comment]
Sounds like a version conflict. What is the version of wxPython installed?

**Comment by arun-gurung** [comment]
I installed wxPython from Manjaro repositories.

python2-wxpython3                                                                                [Installed] 3.0.2.0-3              community 

Now I see that AUR repository also offers some wx packages, among them the Phoenix which I read about some other place about the "adv" module error.

wxpython-phoenix-git                                                                                         r3413.f04d103b-3       AUR

**Comment by suurjaak** [comment]
Skyperious requires wxPython 4. 

wxpython-phoenix-git seems to be for Python 3, which Skyperious does not support yet. 

When I was testing live sync on Manjaro, I used pip to install Skyperious and its dependencies, i.e. `pip2 install skyperious`. It built the wxPython installation locally during this (that took some time).

**Comment by arun-gurung** [comment]
That's a great way to install Skyperious, but it took a long time with wxPython! Now it can find my main chat and I can export also, but even when I save it, the file chooser says it's a HTML-file, but the export is just a plain text file?

**Comment by arun-gurung** [comment]
OK thanks for another workaround.

Before you close the issue, I just wanna know why you can export pictures but no videos, PDFs or other documents?
